Repository uiowa/uiowa, pull requests merged in 2019-12, with the labels that each got.

#782 Link to edit webform embedded in paragraphs
  docroot/modules/custom/sitenow_paragraphs/sitenow_paragraphs.module
Labels: enhancement

#876 Update simple_sitemap module
  composer.json
  composer.lock
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.bundle_settings.default.node.article.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.bundle_settings.default.node.page.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.bundle_settings.default.node.person.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.bundle_settings.node.article.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.bundle_settings.node.person.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.custom_links.default.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.settings.yml
  docroot/profiles/custom/sitenow/config/sync/simple_sitemap.variants.default_hreflang.yml
Labels: composer update, database update, sitenow profile

#882 Provision climatecollective
  config/climatecollective.uiowa.edu/.gitkeep
  docroot/sites/climatecollective.uiowa.edu/blt.yml
  docroot/sites/climatecollective.uiowa.edu/default.local.drush.yml
  docroot/sites/climatecollective.uiowa.edu/default.settings.php
  docroot/sites/climatecollective.uiowa.edu/settings.php
  docroot/sites/climatecollective.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/climatecollective.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/climatecollective.site.yml
Labels: provision
