Repository uiowa/uiowa, pull requests merged in 2020-01, with the labels that each got.

#886 Cnm provision
  config/cnm.uiowa.edu/.gitkeep
  docroot/sites/cnm.uiowa.edu/blt.yml
  docroot/sites/cnm.uiowa.edu/default.local.drush.yml
  docroot/sites/cnm.uiowa.edu/default.settings.php
  docroot/sites/cnm.uiowa.edu/settings.php
  docroot/sites/cnm.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/cnm.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/cnm.site.yml
Labels: provision

#897 Deprovision uiobl
  config/uiobl.org.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/uiobl.org.uiowa.edu/blt.yml
  docroot/sites/uiobl.org.uiowa.edu/default.local.drush.yml
  docroot/sites/uiobl.org.uiowa.edu/default.settings.php
  docroot/sites/uiobl.org.uiowa.edu/settings.php
  docroot/sites/uiobl.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/uiobl.org.uiowa.edu/settings/default.local.settings.php
  drush/sites/orguiobl.site.yml
Labels: deprovision

#899 1 8 20 provision
  config/ICRU.research.uiowa.edu/.gitkeep
  config/businsvc.fo.uiowa.edu/.gitkeep
  config/ighn.international.uiowa.edu/.gitkeep
  docroot/sites/ICRU.research.uiowa.edu/blt.yml
  docroot/sites/ICRU.research.uiowa.edu/default.local.drush.yml
  docroot/sites/ICRU.research.uiowa.edu/default.settings.php
  docroot/sites/ICRU.research.uiowa.edu/settings.php
  docroot/sites/ICRU.research.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/ICRU.research.uiowa.edu/settings/default.local.settings.php
  docroot/sites/businsvc.fo.uiowa.edu/blt.yml
  docroot/sites/businsvc.fo.uiowa.edu/default.local.drush.yml
  docroot/sites/businsvc.fo.uiowa.edu/default.settings.php
  docroot/sites/businsvc.fo.uiowa.edu/settings.php
  docroot/sites/businsvc.fo.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/businsvc.fo.uiowa.edu/settings/default.local.settings.php
  docroot/sites/ighn.international.uiowa.edu/blt.yml
  docroot/sites/ighn.international.uiowa.edu/default.local.drush.yml
  docroot/sites/ighn.international.uiowa.edu/default.settings.php
  docroot/sites/ighn.international.uiowa.edu/settings.php
  docroot/sites/ighn.international.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/ighn.international.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/fobusinsvc.site.yml
  drush/sites/internationalighn.site.yml
  drush/sites/researchICRU.site.yml
Labels: provision

#910 Provision jan9
  config/conflictmanagement.org.uiowa.edu/.gitkeep
  config/designcenter.uiowa.edu/.gitkeep
  docroot/sites/conflictmanagement.org.uiowa.edu/blt.yml
  docroot/sites/conflictmanagement.org.uiowa.edu/default.local.drush.yml
  docroot/sites/conflictmanagement.org.uiowa.edu/default.settings.php
  docroot/sites/conflictmanagement.org.uiowa.edu/settings.php
  docroot/sites/conflictmanagement.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/conflictmanagement.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/designcenter.uiowa.edu/blt.yml
  docroot/sites/designcenter.uiowa.edu/default.local.drush.yml
  docroot/sites/designcenter.uiowa.edu/default.settings.php
  docroot/sites/designcenter.uiowa.edu/settings.php
  docroot/sites/designcenter.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/designcenter.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/designcenter.site.yml
  drush/sites/orgconflictmanagement.site.yml
Labels: provision

#908 Deprovision uppercase site ICRU.research.uiowa.edu
  config/ICRU.research.uiowa.edu/.gitkeep
  docroot/sites/ICRU.research.uiowa.edu/blt.yml
  docroot/sites/ICRU.research.uiowa.edu/default.local.drush.yml
  docroot/sites/ICRU.research.uiowa.edu/default.settings.php
  docroot/sites/ICRU.research.uiowa.edu/settings.php
  docroot/sites/ICRU.research.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/ICRU.research.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/researchICRU.site.yml
Labels: deprovision

#909 Brand - Lockup Round 3a
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.services.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/css/lockup-preview.css
  docroot/sites/brand.uiowa.edu/modules/brand_core/js/lockup-preview.behaviors.js
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Theme/LockupForm.php
  docroot/sites/brand.uiowa.edu/modules/brand_core/templates/form--lockup.html.twig
Labels: brand.uiowa.edu

#913 Provision icru
  config/icru.research.uiowa.edu/.gitkeep
  docroot/sites/icru.research.uiowa.edu/blt.yml
  docroot/sites/icru.research.uiowa.edu/default.local.drush.yml
  docroot/sites/icru.research.uiowa.edu/default.settings.php
  docroot/sites/icru.research.uiowa.edu/settings.php
  docroot/sites/icru.research.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/icru.research.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/researchicru.site.yml
Labels: provision

#914 Brand - Lockup Round 3b
  config/brand.uiowa.edu/user.role.collaborator.yml
  config/brand.uiowa.edu/views.view.lockup_moderation.yml
  config/brand.uiowa.edu/views.view.lockups.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.libraries.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.links.menu.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.links.task.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/css/lockup-preview.css
  docroot/sites/brand.uiowa.edu/modules/brand_core/css/toolbar-overrides.css
  docroot/sites/brand.uiowa.edu/modules/brand_core/fonts/RobotoBold.svg
  docroot/sites/brand.uiowa.edu/modules/brand_core/fonts/RobotoRegular.svg
  docroot/sites/brand.uiowa.edu/modules/brand_core/js/lockup-preview.behaviors.js
  docroot/sites/brand.uiowa.edu/modules/brand_core/templates/node--lockup--full.html.twig
Labels: brand.uiowa.edu

#917 Brand - Lockup Round 3c
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php
Labels: brand.uiowa.edu

#945 i944 Update Request a Site - Hostmaster Top Level email
  config/sitenow.uiowa.edu/webform.webform.request_a_site.yml
Labels: sitenow.uiowa.edu

#947 Early morning provisions Jan 17
  config/sustainabilitycommittee.uiowa.edu/.gitkeep
  config/sustainabiltycommittee.uiowa.edu/.gitkeep
  config/talbert.lab.uiowa.edu/.gitkeep
  config/university-shared-services.fo.uiowa.edu/.gitkeep
  config/voice-academy.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/sustainabilitycommittee.uiowa.edu/blt.yml
  docroot/sites/sustainabilitycommittee.uiowa.edu/default.local.drush.yml
  docroot/sites/sustainabilitycommittee.uiowa.edu/default.settings.php
  docroot/sites/sustainabilitycommittee.uiowa.edu/settings.php
  docroot/sites/sustainabilitycommittee.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/sustainabilitycommittee.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sustainabilitycommittee.uiowa.edu/settings/includes.settings.php
  docroot/sites/talbert.lab.uiowa.edu/blt.yml
  docroot/sites/talbert.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/talbert.lab.uiowa.edu/default.settings.php
  docroot/sites/talbert.lab.uiowa.edu/settings.php
  docroot/sites/talbert.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/talbert.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/talbert.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/university-shared-services.fo.uiowa.edu/blt.yml
  docroot/sites/university-shared-services.fo.uiowa.edu/default.local.drush.yml
  docroot/sites/university-shared-services.fo.uiowa.edu/default.settings.php
  docroot/sites/university-shared-services.fo.uiowa.edu/settings.php
  docroot/sites/university-shared-services.fo.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/university-shared-services.fo.uiowa.edu/settings/default.local.settings.php
  docroot/sites/university-shared-services.fo.uiowa.edu/settings/includes.settings.php
  docroot/sites/voice-academy.uiowa.edu/blt.yml
  docroot/sites/voice-academy.uiowa.edu/default.local.drush.yml
  docroot/sites/voice-academy.uiowa.edu/default.settings.php
  docroot/sites/voice-academy.uiowa.edu/settings.php
  docroot/sites/voice-academy.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/voice-academy.uiowa.edu/settings/default.local.settings.php
  docroot/sites/voice-academy.uiowa.edu/settings/includes.settings.php
  drush/sites/founiversity-shared-services.site.yml
  drush/sites/labtalbert.site.yml
  drush/sites/sustainabilitycommittee.site.yml
  drush/sites/voice-academy.site.yml
Labels: provision

#953 Provision matfab.research.uiowa.edu
  config/matfab.research.uiowa.edu/.gitkeep
  docroot/sites/matfab.research.uiowa.edu/blt.yml
  docroot/sites/matfab.research.uiowa.edu/default.local.drush.yml
  docroot/sites/matfab.research.uiowa.edu/default.settings.php
  docroot/sites/matfab.research.uiowa.edu/settings.php
  docroot/sites/matfab.research.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/matfab.research.uiowa.edu/settings/default.local.settings.php
  docroot/sites/matfab.research.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/researchmatfab.site.yml
Labels: provision

#963 Feature: Updates settings files for sites on uiowa01.
  docroot/sites/cogscilang.grad.uiowa.edu/settings.php
  docroot/sites/icsa.uiowa.edu/settings.php
  docroot/sites/iowasuperfund.uiowa.edu/settings.php
  docroot/sites/policy.clas.uiowa.edu/settings.php
  docroot/sites/uipda.grad.uiowa.edu/settings.php
  tests/phpunit/src/Unit/FilesystemTest.php
Labels: bug

#946 i924 - SiteNow Training Registration Form
  config/sitenow.uiowa.edu/webform.webform.training_registration_form.yml
Labels: sitenow.uiowa.edu

#973 Provision autismcenter.centerforconferences.uiowa.edu
  config/autismcenter.centerforconferences.uiowa.edu/.gitkeep
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/blt.yml
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/default.local.drush.yml
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/default.settings.php
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/settings.php
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/settings/default.local.settings.php
  docroot/sites/autismcenter.centerforconferences.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/centerforconferencesautismcenter.site.yml
Labels: provision

#920 Brand - Lockup Round 3d
  config/brand.uiowa.edu/field.field.node.lockup.field_lockup_p_unit_stacked.yml
  config/brand.uiowa.edu/field.field.node.lockup.field_lockup_primary_unit.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.install
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php
  docroot/sites/brand.uiowa.edu/modules/brand_core/templates/form--lockup.html.twig
Labels: brand.uiowa.edu

#999 Only use existing-config option if using sitenow profile.
  blt/src/Blt/Plugin/Commands/ReplaceCommands.php
Labels: automation, bug, collegiate profile
