Repository uiowa/uiowa, pull requests merged in 2020-02, with the labels that each got.

#1004 Provisions Feb 3rd
  box/config.yml
  config/assist.org.uiowa.edu/.gitkeep
  config/audit.org.uiowa.edu/.gitkeep
  config/cognitivecontrol.psychology.uiowa.edu/.gitkeep
  config/museumstudies.sites.uiowa.edu/.gitkeep
  config/ui-lsamp.sites.uiowa.edu/.gitkeep
  config/wise.org.uiowa.edu/.gitkeep
  docroot/sites/assist.org.uiowa.edu/blt.yml
  docroot/sites/assist.org.uiowa.edu/default.local.drush.yml
  docroot/sites/assist.org.uiowa.edu/default.settings.php
  docroot/sites/assist.org.uiowa.edu/settings.php
  docroot/sites/assist.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/assist.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/assist.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/audit.org.uiowa.edu/blt.yml
  docroot/sites/audit.org.uiowa.edu/default.local.drush.yml
  docroot/sites/audit.org.uiowa.edu/default.settings.php
  docroot/sites/audit.org.uiowa.edu/settings.php
  docroot/sites/audit.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/audit.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/audit.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/blt.yml
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/default.local.drush.yml
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/default.settings.php
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/settings.php
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/settings/default.local.settings.php
  docroot/sites/cognitivecontrol.psychology.uiowa.edu/settings/includes.settings.php
  docroot/sites/museumstudies.sites.uiowa.edu/blt.yml
  docroot/sites/museumstudies.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/museumstudies.sites.uiowa.edu/default.settings.php
  docroot/sites/museumstudies.sites.uiowa.edu/settings.php
  docroot/sites/museumstudies.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/museumstudies.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/museumstudies.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  docroot/sites/ui-lsamp.sites.uiowa.edu/blt.yml
  docroot/sites/ui-lsamp.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/ui-lsamp.sites.uiowa.edu/default.settings.php
  docroot/sites/ui-lsamp.sites.uiowa.edu/settings.php
  docroot/sites/ui-lsamp.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/ui-lsamp.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/ui-lsamp.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/wise.org.uiowa.edu/blt.yml
  docroot/sites/wise.org.uiowa.edu/default.local.drush.yml
  docroot/sites/wise.org.uiowa.edu/default.settings.php
  docroot/sites/wise.org.uiowa.edu/settings.php
  docroot/sites/wise.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/wise.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/wise.org.uiowa.edu/settings/includes.settings.php
  drush/sites/orgassist.site.yml
  drush/sites/orgaudit.site.yml
  drush/sites/orgwise.site.yml
  drush/sites/psychologycognitivecontrol.site.yml
  drush/sites/sitesmuseumstudies.site.yml
  drush/sites/sitesui-lsamp.site.yml
Labels: provision

#1007 style for nolink option #1006
  docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/blocks/_block-superfish.scss
Labels: sitenow profile, theming

#1011 Provisions Feb 6
  box/config.yml
  config/coepe.uiowa.edu/.gitkeep
  config/computational-symposium.psychiatry.uiowa.edu/.gitkeep
  config/miles.lab.uiowa.edu/.gitkeep
  docroot/sites/coepe.uiowa.edu/blt.yml
  docroot/sites/coepe.uiowa.edu/default.local.drush.yml
  docroot/sites/coepe.uiowa.edu/default.settings.php
  docroot/sites/coepe.uiowa.edu/settings.php
  docroot/sites/coepe.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/coepe.uiowa.edu/settings/default.local.settings.php
  docroot/sites/coepe.uiowa.edu/settings/includes.settings.php
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/blt.yml
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/default.local.drush.yml
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/default.settings.php
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/settings.php
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/settings/default.local.settings.php
  docroot/sites/computational-symposium.psychiatry.uiowa.edu/settings/includes.settings.php
  docroot/sites/miles.lab.uiowa.edu/blt.yml
  docroot/sites/miles.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/miles.lab.uiowa.edu/default.settings.php
  docroot/sites/miles.lab.uiowa.edu/settings.php
  docroot/sites/miles.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/miles.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/miles.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/coepe.site.yml
  drush/sites/labmiles.site.yml
  drush/sites/psychiatrycomputational-symposium.site.yml
Labels: provision

#1014 Initialize moyerowley.lab.uiowa.edu multisite
  box/config.yml
  config/advising.uiowa.edu/.gitkeep
  config/moyerowley.lab.uiowa.edu/.gitkeep
  docroot/sites/advising.uiowa.edu/blt.yml
  docroot/sites/advising.uiowa.edu/default.local.drush.yml
  docroot/sites/advising.uiowa.edu/default.settings.php
  docroot/sites/advising.uiowa.edu/settings.php
  docroot/sites/advising.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/advising.uiowa.edu/settings/default.local.settings.php
  docroot/sites/advising.uiowa.edu/settings/includes.settings.php
  docroot/sites/moyerowley.lab.uiowa.edu/blt.yml
  docroot/sites/moyerowley.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/moyerowley.lab.uiowa.edu/default.settings.php
  docroot/sites/moyerowley.lab.uiowa.edu/settings.php
  docroot/sites/moyerowley.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/moyerowley.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/moyerowley.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/advising.site.yml
  drush/sites/labmoyerowley.site.yml
Labels: provision

#1015 Initialize adsforruralamerica.uiowa.edu multisite
  box/config.yml
  config/adsforruralamerica.uiowa.edu/.gitkeep
  config/horn.studio.uiowa.edu/.gitkeep
  config/idrs2020.org/.gitkeep
  docroot/sites/adsforruralamerica.uiowa.edu/blt.yml
  docroot/sites/adsforruralamerica.uiowa.edu/default.local.drush.yml
  docroot/sites/adsforruralamerica.uiowa.edu/default.settings.php
  docroot/sites/adsforruralamerica.uiowa.edu/settings.php
  docroot/sites/adsforruralamerica.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/adsforruralamerica.uiowa.edu/settings/default.local.settings.php
  docroot/sites/adsforruralamerica.uiowa.edu/settings/includes.settings.php
  docroot/sites/horn.studio.uiowa.edu/blt.yml
  docroot/sites/horn.studio.uiowa.edu/default.local.drush.yml
  docroot/sites/horn.studio.uiowa.edu/default.settings.php
  docroot/sites/horn.studio.uiowa.edu/settings.php
  docroot/sites/horn.studio.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/horn.studio.uiowa.edu/settings/default.local.settings.php
  docroot/sites/horn.studio.uiowa.edu/settings/includes.settings.php
  docroot/sites/idrs2020.org/blt.yml
  docroot/sites/idrs2020.org/default.local.drush.yml
  docroot/sites/idrs2020.org/default.settings.php
  docroot/sites/idrs2020.org/settings.php
  docroot/sites/idrs2020.org/settings/default.includes.settings.php
  docroot/sites/idrs2020.org/settings/default.local.settings.php
  docroot/sites/idrs2020.org/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/adsforruralamerica.site.yml
  drush/sites/org-idrs2020.site.yml
  drush/sites/studiohorn.site.yml
Labels: provision

#1021 Provision uiowa.edu
  blt/src/Multisite.php
  box/config.yml
  config/uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/uiowa.edu/blt.yml
  docroot/sites/uiowa.edu/default.local.drush.yml
  docroot/sites/uiowa.edu/default.settings.php
  docroot/sites/uiowa.edu/settings.php
  docroot/sites/uiowa.edu/settings/default.includes.settings.php
  docroot/sites/uiowa.edu/settings/default.local.settings.php
  docroot/sites/uiowa.edu/settings/includes.settings.php
  drush/sites/home.site.yml
Labels: provision

#1024 Provisions Feb 7
  box/config.yml
  config/cbig.iibi.uiowa.edu/.gitkeep
  config/crisp.org.uiowa.edu/.gitkeep
  config/irbr.org.uiowa.edu/.gitkeep
  docroot/sites/cbig.iibi.uiowa.edu/blt.yml
  docroot/sites/cbig.iibi.uiowa.edu/default.local.drush.yml
  docroot/sites/cbig.iibi.uiowa.edu/default.settings.php
  docroot/sites/cbig.iibi.uiowa.edu/settings.php
  docroot/sites/cbig.iibi.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/cbig.iibi.uiowa.edu/settings/default.local.settings.php
  docroot/sites/cbig.iibi.uiowa.edu/settings/includes.settings.php
  docroot/sites/crisp.org.uiowa.edu/blt.yml
  docroot/sites/crisp.org.uiowa.edu/default.local.drush.yml
  docroot/sites/crisp.org.uiowa.edu/default.settings.php
  docroot/sites/crisp.org.uiowa.edu/settings.php
  docroot/sites/crisp.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/crisp.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/crisp.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/irbr.org.uiowa.edu/blt.yml
  docroot/sites/irbr.org.uiowa.edu/default.local.drush.yml
  docroot/sites/irbr.org.uiowa.edu/default.settings.php
  docroot/sites/irbr.org.uiowa.edu/settings.php
  docroot/sites/irbr.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/irbr.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/irbr.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/iibicbig.site.yml
  drush/sites/orgcrisp.site.yml
  drush/sites/orgirbr.site.yml
Labels: provision

#1025 Initialize nightatthesciencelabs.conference.uiowa.edu multisite
  box/config.yml
  config/nightatthesciencelabs.conference.uiowa.edu/.gitkeep
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/blt.yml
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/default.local.drush.yml
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/default.settings.php
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/settings.php
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/settings/default.local.settings.php
  docroot/sites/nightatthesciencelabs.conference.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/conferencenightatthesciencelabs.site.yml
Labels: provision

#1031 Initialize dasblatt.sites.uiowa.edu multisite
  box/config.yml
  config/dasblatt.sites.uiowa.edu/.gitkeep
  docroot/sites/dasblatt.sites.uiowa.edu/blt.yml
  docroot/sites/dasblatt.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/dasblatt.sites.uiowa.edu/default.settings.php
  docroot/sites/dasblatt.sites.uiowa.edu/settings.php
  docroot/sites/dasblatt.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/dasblatt.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/dasblatt.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/sitesdasblatt.site.yml
Labels: provision

#1044 Ignore the SiteNow people view
  docroot/profiles/custom/sitenow/config/sync/config_ignore.settings.yml
Labels: bug, sitenow profile

#1036 Brand Round 4a
  config/brand.uiowa.edu/core.base_field_override.node.lockup.title.yml
  config/brand.uiowa.edu/field.field.node.lockup.field_lockup_p_unit_stacked.yml
  config/brand.uiowa.edu/field.field.node.lockup.field_lockup_primary_unit.yml
  config/brand.uiowa.edu/field.field.node.lockup.field_lockup_s_unit_stacked.yml
  config/brand.uiowa.edu/field.field.node.lockup.field_lockup_sub_unit.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.links.menu.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.routing.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/fonts/RobotoBold.svg
  docroot/sites/brand.uiowa.edu/modules/brand_core/fonts/RobotoRegular.svg
  docroot/sites/brand.uiowa.edu/modules/brand_core/templates/node--lockup--full.html.twig
Labels: brand.uiowa.edu

#1055 Initialize trans-resources.org.uiowa.edu multisite
  box/config.yml
  config/trans-resources.org.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/trans-resources.org.uiowa.edu/blt.yml
  docroot/sites/trans-resources.org.uiowa.edu/default.local.drush.yml
  docroot/sites/trans-resources.org.uiowa.edu/default.settings.php
  docroot/sites/trans-resources.org.uiowa.edu/settings.php
  docroot/sites/trans-resources.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/trans-resources.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/trans-resources.org.uiowa.edu/settings/includes.settings.php
  drush/sites/orgtrans-resources.site.yml
Labels: provision

#1050 Brand Round 4b
  config/brand.uiowa.edu/user.role.collaborator.yml
  config/brand.uiowa.edu/views.view.lockup_moderation.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/css/lockup-preview.css
  docroot/sites/brand.uiowa.edu/modules/brand_core/js/lockup-preview.behaviors.js
Labels: brand.uiowa.edu

#1065 Return exit code 1 on Gulp task failures.
  docroot/themes/custom/collegiate_theme/gulpfile.js
  docroot/themes/custom/uids_base/gulpfile.js
  docroot/themes/custom/uids_base/scss/components/global/menus/mega-menu/mega-menu.scss
  docroot/themes/custom/uiowa_bootstrap/gulpfile.js
Labels: help wanted, theming

#1068 Feb 14 night provisions
  box/config.yml
  config/paleorepository.sites.uiowa.edu/.gitkeep
  config/researchcollections.sites.uiowa.edu/.gitkeep
  docroot/sites/paleorepository.sites.uiowa.edu/blt.yml
  docroot/sites/paleorepository.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/paleorepository.sites.uiowa.edu/default.settings.php
  docroot/sites/paleorepository.sites.uiowa.edu/settings.php
  docroot/sites/paleorepository.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/paleorepository.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/paleorepository.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/researchcollections.sites.uiowa.edu/blt.yml
  docroot/sites/researchcollections.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/researchcollections.sites.uiowa.edu/default.settings.php
  docroot/sites/researchcollections.sites.uiowa.edu/settings.php
  docroot/sites/researchcollections.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/researchcollections.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/researchcollections.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/sitespaleorepository.site.yml
  drush/sites/sitesresearchcollections.site.yml
Labels: provision

#1070 Initialize sbirt.uiowa.edu multisite
  box/config.yml
  config/sbirt.uiowa.edu/.gitkeep
  docroot/sites/sbirt.uiowa.edu/blt.yml
  docroot/sites/sbirt.uiowa.edu/default.local.drush.yml
  docroot/sites/sbirt.uiowa.edu/default.settings.php
  docroot/sites/sbirt.uiowa.edu/settings.php
  docroot/sites/sbirt.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/sbirt.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sbirt.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/sbirt.site.yml
Labels: provision

#1074 Provisions 2 18
  box/config.yml
  config/critical-incident-plan.sites.uiowa.edu/.gitkeep
  config/fallgiving.sites.uiowa.edu/.gitkeep
  config/mural-film.sites.uiowa.edu/.gitkeep
  config/statefair.sites.uiowa.edu/.gitkeep
  docroot/sites/critical-incident-plan.sites.uiowa.edu/blt.yml
  docroot/sites/critical-incident-plan.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/critical-incident-plan.sites.uiowa.edu/default.settings.php
  docroot/sites/critical-incident-plan.sites.uiowa.edu/settings.php
  docroot/sites/critical-incident-plan.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/critical-incident-plan.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/critical-incident-plan.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/fallgiving.sites.uiowa.edu/blt.yml
  docroot/sites/fallgiving.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/fallgiving.sites.uiowa.edu/default.settings.php
  docroot/sites/fallgiving.sites.uiowa.edu/settings.php
  docroot/sites/fallgiving.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/fallgiving.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/fallgiving.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/mural-film.sites.uiowa.edu/blt.yml
  docroot/sites/mural-film.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/mural-film.sites.uiowa.edu/default.settings.php
  docroot/sites/mural-film.sites.uiowa.edu/settings.php
  docroot/sites/mural-film.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/mural-film.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/mural-film.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  docroot/sites/statefair.sites.uiowa.edu/blt.yml
  docroot/sites/statefair.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/statefair.sites.uiowa.edu/default.settings.php
  docroot/sites/statefair.sites.uiowa.edu/settings.php
  docroot/sites/statefair.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/statefair.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/statefair.sites.uiowa.edu/settings/includes.settings.php
  drush/sites/sitescritical-incident-plan.site.yml
  drush/sites/sitesfallgiving.site.yml
  drush/sites/sitesmural-film.site.yml
  drush/sites/sitesstatefair.site.yml
Labels: provision

#1077 Provisions Feb 19
  box/config.yml
  config/auditoryresearch.lab.uiowa.edu/.gitkeep
  config/bmess.org.uiowa.edu/.gitkeep
  config/lentz.lab.uiowa.edu/.gitkeep
  docroot/sites/auditoryresearch.lab.uiowa.edu/blt.yml
  docroot/sites/auditoryresearch.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/auditoryresearch.lab.uiowa.edu/default.settings.php
  docroot/sites/auditoryresearch.lab.uiowa.edu/settings.php
  docroot/sites/auditoryresearch.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/auditoryresearch.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/auditoryresearch.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/bmess.org.uiowa.edu/blt.yml
  docroot/sites/bmess.org.uiowa.edu/default.local.drush.yml
  docroot/sites/bmess.org.uiowa.edu/default.settings.php
  docroot/sites/bmess.org.uiowa.edu/settings.php
  docroot/sites/bmess.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/bmess.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/bmess.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/lentz.lab.uiowa.edu/blt.yml
  docroot/sites/lentz.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/lentz.lab.uiowa.edu/default.settings.php
  docroot/sites/lentz.lab.uiowa.edu/settings.php
  docroot/sites/lentz.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/lentz.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/lentz.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/labauditoryresearch.site.yml
  drush/sites/lablentz.site.yml
  drush/sites/orgbmess.site.yml
Labels: provision

#1079 Initialize debate.uiowa.edu multisite
  box/config.yml
  config/debate.uiowa.edu/.gitkeep
  docroot/sites/debate.uiowa.edu/blt.yml
  docroot/sites/debate.uiowa.edu/default.local.drush.yml
  docroot/sites/debate.uiowa.edu/default.settings.php
  docroot/sites/debate.uiowa.edu/settings.php
  docroot/sites/debate.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/debate.uiowa.edu/settings/default.local.settings.php
  docroot/sites/debate.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/debate.site.yml
Labels: provision

#1084 Initialize grueter.lab.uiowa.edu multisite
  box/config.yml
  config/grueter.lab.uiowa.edu/.gitkeep
  config/movementfellowship.sites.uiowa.edu/.gitkeep
  config/postsecular-novel.sites.uiowa.edu/.gitkeep
  docroot/sites/grueter.lab.uiowa.edu/blt.yml
  docroot/sites/grueter.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/grueter.lab.uiowa.edu/default.settings.php
  docroot/sites/grueter.lab.uiowa.edu/settings.php
  docroot/sites/grueter.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/grueter.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/grueter.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/movementfellowship.sites.uiowa.edu/blt.yml
  docroot/sites/movementfellowship.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/movementfellowship.sites.uiowa.edu/default.settings.php
  docroot/sites/movementfellowship.sites.uiowa.edu/settings.php
  docroot/sites/movementfellowship.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/movementfellowship.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/movementfellowship.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/postsecular-novel.sites.uiowa.edu/blt.yml
  docroot/sites/postsecular-novel.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/postsecular-novel.sites.uiowa.edu/default.settings.php
  docroot/sites/postsecular-novel.sites.uiowa.edu/settings.php
  docroot/sites/postsecular-novel.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/postsecular-novel.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/postsecular-novel.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/labgrueter.site.yml
  drush/sites/sitesmovementfellowship.site.yml
  drush/sites/sitespostsecular-novel.site.yml
Labels: provision

#1080 Brand Round 4d
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php
Labels: brand.uiowa.edu

#1087 Initialize geriatricpain.org multisite
  box/config.yml
  config/geriatricpain.org/.gitkeep
  config/igec.uiowa.edu/.gitkeep
  docroot/sites/geriatricpain.org/blt.yml
  docroot/sites/geriatricpain.org/default.local.drush.yml
  docroot/sites/geriatricpain.org/default.settings.php
  docroot/sites/geriatricpain.org/settings.php
  docroot/sites/geriatricpain.org/settings/default.includes.settings.php
  docroot/sites/geriatricpain.org/settings/default.local.settings.php
  docroot/sites/geriatricpain.org/settings/includes.settings.php
  docroot/sites/igec.uiowa.edu/blt.yml
  docroot/sites/igec.uiowa.edu/default.local.drush.yml
  docroot/sites/igec.uiowa.edu/default.settings.php
  docroot/sites/igec.uiowa.edu/settings.php
  docroot/sites/igec.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/igec.uiowa.edu/settings/default.local.settings.php
  docroot/sites/igec.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/igec.site.yml
  drush/sites/org-geriatricpain.site.yml
Labels: provision

#1094 Feb 21 provisions
  box/config.yml
  config/ippl.sites.uiowa.edu/.gitkeep
  config/languagetech.lab.uiowa.edu/.gitkeep
  config/wni.sites.uiowa.edu/.gitkeep
  docroot/sites/ippl.sites.uiowa.edu/blt.yml
  docroot/sites/ippl.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/ippl.sites.uiowa.edu/default.settings.php
  docroot/sites/ippl.sites.uiowa.edu/settings.php
  docroot/sites/ippl.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/ippl.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/ippl.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/languagetech.lab.uiowa.edu/blt.yml
  docroot/sites/languagetech.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/languagetech.lab.uiowa.edu/default.settings.php
  docroot/sites/languagetech.lab.uiowa.edu/settings.php
  docroot/sites/languagetech.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/languagetech.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/languagetech.lab.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  docroot/sites/wni.sites.uiowa.edu/blt.yml
  docroot/sites/wni.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/wni.sites.uiowa.edu/default.settings.php
  docroot/sites/wni.sites.uiowa.edu/settings.php
  docroot/sites/wni.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/wni.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/wni.sites.uiowa.edu/settings/includes.settings.php
  drush/sites/lablanguagetech.site.yml
  drush/sites/sitesippl.site.yml
  drush/sites/siteswni.site.yml
Labels: provision

#1097 Initialize indiancinema.sites.uiowa.edu multisite
  box/config.yml
  config/indiancinema.sites.uiowa.edu/.gitkeep
  docroot/sites/indiancinema.sites.uiowa.edu/blt.yml
  docroot/sites/indiancinema.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/indiancinema.sites.uiowa.edu/default.settings.php
  docroot/sites/indiancinema.sites.uiowa.edu/settings.php
  docroot/sites/indiancinema.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/indiancinema.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/indiancinema.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/sitesindiancinema.site.yml
Labels: provision

#1099 Initialize latinxcouncil.uiowa.edu multisite
  box/config.yml
  config/latinxcouncil.uiowa.edu/.gitkeep
  docroot/sites/latinxcouncil.uiowa.edu/blt.yml
  docroot/sites/latinxcouncil.uiowa.edu/default.local.drush.yml
  docroot/sites/latinxcouncil.uiowa.edu/default.settings.php
  docroot/sites/latinxcouncil.uiowa.edu/settings.php
  docroot/sites/latinxcouncil.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/latinxcouncil.uiowa.edu/settings/default.local.settings.php
  docroot/sites/latinxcouncil.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/latinxcouncil.site.yml
Labels: provision

#1102 Brand - Update lockup generator font files
  docroot/sites/brand.uiowa.edu/modules/brand_core/fonts/RobotoBold.svg
  docroot/sites/brand.uiowa.edu/modules/brand_core/fonts/RobotoRegular.svg
Labels: brand.uiowa.edu

#1049 ighn.international.uiowa.edu custom development
  config/ighn.international.uiowa.edu/.htaccess
  config/ighn.international.uiowa.edu/config_split.config_split.ighn.yml
  config/ighn.international.uiowa.edu/core.entity_form_display.node.ighn_person.default.yml
  config/ighn.international.uiowa.edu/core.entity_view_display.node.ighn_person.default.yml
  config/ighn.international.uiowa.edu/core.entity_view_display.node.ighn_person.full.yml
  config/ighn.international.uiowa.edu/core.entity_view_display.node.ighn_person.teaser.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_biography.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_credentials.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_cv_link.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_department.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_first_name.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_focus_areas.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_global_regions.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_image.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_language.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_last_name.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_position_title.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_person_profile_link.yml
  config/ighn.international.uiowa.edu/field.field.node.ighn_person.field_ighn_primary_college.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_biography.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_credentials.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_cv_link.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_department.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_first_name.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_focus_areas.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_global_regions.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_image.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_language.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_last_name.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_position_title.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_person_profile_link.yml
  config/ighn.international.uiowa.edu/field.storage.node.field_ighn_primary_college.yml
  config/ighn.international.uiowa.edu/node.type.ighn_person.yml
  config/ighn.international.uiowa.edu/system.site.yml
  config/ighn.international.uiowa.edu/taxonomy.vocabulary.ighn_department.yml
  config/ighn.international.uiowa.edu/taxonomy.vocabulary.ighn_global_regions.yml
  config/ighn.international.uiowa.edu/taxonomy.vocabulary.ighn_language_expertise.yml
  config/ighn.international.uiowa.edu/taxonomy.vocabulary.ighn_primary_college.yml
  config/ighn.international.uiowa.edu/taxonomy.vocabulary.ighn_primary_focus_areas.yml
  config/ighn.international.uiowa.edu/views.view.ighn_person_view.yml
  docroot/profiles/custom/sitenow/config/sync/fontawesome.settings.yml
  docroot/profiles/custom/sitenow/config/sync/views.view.people.yml
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/assets/css/ighn.css
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/ighn_core.info.yml
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/ighn_core.install
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/ighn_core.libraries.yml
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/ighn_core.module
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/node--ighn-person--full.html.twig
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/node--ighn-person--teaser.html.twig
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/node.html.twig
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/templates/views-view-unformatted--ighn-person-view.html.twig
Labels: ighn.international.uiowa.edu

#1109 Set up config_ignore for uiowa.edu.
  config/uiowa.edu/config_ignore.settings.yml
  config/uiowa.edu/config_snapshot.snapshot.config_sync.module.config_ignore.yml
  config/uiowa.edu/config_snapshot.snapshot.config_sync.module.menu_admin_per_menu.yml
  config/uiowa.edu/core.extension.yml
  config/uiowa.edu/user.role.editor.yml
  config/uiowa.edu/user.role.webmaster.yml
Labels: enhancement, uiowa.edu

#1108 Update uiowa.edu metatags permissions.
  config/uiowa.edu/metatag.metatag_defaults.node.yml
  config/uiowa.edu/user.role.editor.yml
  config/uiowa.edu/user.role.webmaster.yml
Labels: enhancement, uiowa.edu

#1103 Feature: uiowa.edu layout builder permissions
  config/uiowa.edu/user.role.editor.yml
  config/uiowa.edu/user.role.webmaster.yml
  docroot/profiles/custom/collegiate/config/install/user.role.editor.yml
  docroot/profiles/custom/collegiate/config/install/user.role.webmaster.yml
Labels: collegiate profile, homepage

#1111 hpproject - set front and prevent deletion
  config/uiowa.edu/system.site.yml
  docroot/profiles/custom/collegiate/collegiate.profile
Labels: homepage, uiowa.edu

#1117 Provisions Feb 27
  box/config.yml
  config/coronavirus.uiowa.edu/.gitkeep
  config/datascience-workshop.uiowa.edu/.gitkeep
  config/legalclinic.org.uiowa.edu/.gitkeep
  config/liberalartsbeyondbars.sites.uiowa.edu/.gitkeep
  docroot/sites/coronavirus.uiowa.edu/blt.yml
  docroot/sites/coronavirus.uiowa.edu/default.local.drush.yml
  docroot/sites/coronavirus.uiowa.edu/default.settings.php
  docroot/sites/coronavirus.uiowa.edu/settings.php
  docroot/sites/coronavirus.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/coronavirus.uiowa.edu/settings/default.local.settings.php
  docroot/sites/coronavirus.uiowa.edu/settings/includes.settings.php
  docroot/sites/datascience-workshop.uiowa.edu/blt.yml
  docroot/sites/datascience-workshop.uiowa.edu/default.local.drush.yml
  docroot/sites/datascience-workshop.uiowa.edu/default.settings.php
  docroot/sites/datascience-workshop.uiowa.edu/settings.php
  docroot/sites/datascience-workshop.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/datascience-workshop.uiowa.edu/settings/default.local.settings.php
  docroot/sites/datascience-workshop.uiowa.edu/settings/includes.settings.php
  docroot/sites/legalclinic.org.uiowa.edu/blt.yml
  docroot/sites/legalclinic.org.uiowa.edu/default.local.drush.yml
  docroot/sites/legalclinic.org.uiowa.edu/default.settings.php
  docroot/sites/legalclinic.org.uiowa.edu/settings.php
  docroot/sites/legalclinic.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/legalclinic.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/legalclinic.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/blt.yml
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/default.settings.php
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/settings.php
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/liberalartsbeyondbars.sites.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/coronavirus.site.yml
  drush/sites/datascience-workshop.site.yml
  drush/sites/orglegalclinic.site.yml
  drush/sites/sitesliberalartsbeyondbars.site.yml
Labels: provision

#1123 Provisions Feb 28
  box/config.yml
  config/majorshadowuiowa.org.uiowa.edu/.gitkeep
  config/phibetadelta.org.uiowa.edu/.gitkeep
  docroot/sites/majorshadowuiowa.org.uiowa.edu/blt.yml
  docroot/sites/majorshadowuiowa.org.uiowa.edu/default.local.drush.yml
  docroot/sites/majorshadowuiowa.org.uiowa.edu/default.settings.php
  docroot/sites/majorshadowuiowa.org.uiowa.edu/settings.php
  docroot/sites/majorshadowuiowa.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/majorshadowuiowa.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/majorshadowuiowa.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/phibetadelta.org.uiowa.edu/blt.yml
  docroot/sites/phibetadelta.org.uiowa.edu/default.local.drush.yml
  docroot/sites/phibetadelta.org.uiowa.edu/default.settings.php
  docroot/sites/phibetadelta.org.uiowa.edu/settings.php
  docroot/sites/phibetadelta.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/phibetadelta.org.uiowa.edu/settings/default.local.settings.php
  docroot/sites/phibetadelta.org.uiowa.edu/settings/includes.settings.php
  docroot/sites/sites.php
  drush/sites/orgmajorshadowuiowa.site.yml
  drush/sites/orgphibetadelta.site.yml
Labels: provision
