Repository uiowa/uiowa, pull requests merged in 2021-08, with the labels that each got.

#3901 Fix Brand Lockup Digest
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Commands/BrandCoreCommands.php
Labels: joeing-rogue

#3917 Initialize itu.physics.uiowa.edu multisite on uiowa01
  box/config.yml
  config/itu.physics.uiowa.edu/.gitkeep
  docroot/sites/itu.physics.uiowa.edu/blt.yml
  docroot/sites/itu.physics.uiowa.edu/default.local.drush.yml
  docroot/sites/itu.physics.uiowa.edu/default.settings.php
  docroot/sites/itu.physics.uiowa.edu/settings.php
  docroot/sites/itu.physics.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/itu.physics.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/physicsitu.site.yml
Labels: clas

#3914 Implement redirect from physics.uiowa.edu/~ to homepage.physics.uiowa.edu/~.
  docroot/.htaccess
  patches/core_htaccess.patch
Labels: clas

#3919 Brand - set reply-to for email to keep drupal happy
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
Labels: joeing-rogue

#3995 Genetics: People updates
  config/default/config_split.config_split.grad_person_extended.yml
  config/features/grad_person_extended/core.entity_form_display.node.person.minimal.yml
  config/features/grad_person_extended/core.entity_view_display.node.person.token.yml
  config/genetics.grad.uiowa.edu/.htaccess
  config/genetics.grad.uiowa.edu/config_split.config_split.genetics_grad_uiowa_edu.yml
  config/genetics.grad.uiowa.edu/views.view.person_custom.yml
Labels: grad

#3983 Upgrade to PHP 7.4 and resolve some PHPCS warnings.
  .travis.yml
  box/config.yml
  composer.json
  composer.lock
  docroot/modules/custom/grad_custom/grad_thesis_defense/grad_thesis_defense.module
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php
  docroot/modules/custom/sitenow_migrate/sitenow_migrate.services.yml
  docroot/modules/custom/sitenow_migrate/src/EventSubscriber/PostRowSaveEvent.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/Pages.php
  docroot/modules/custom/sitenow_people/sitenow_people.module
  docroot/modules/custom/sitenow_people/src/PersonTypeInterface.php
  docroot/modules/custom/uiowa_aggregator/uiowa_aggregator.module
  docroot/modules/custom/uiowa_area_of_study/src/Plugin/Block/AreasOfStudySearchBlock.php
  docroot/modules/custom/uiowa_area_of_study/uiowa_area_of_study.install
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.install
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.services.yml
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/EventSubscriber/SectionComponentSubscriber.php
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Form/ScholarshipsJumpMenu.php
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/AdmissionsCounselorsMapBlock.php
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/ScholarshipsBlock.php
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/ScholarshipsJumpMenuBlock.php
  docroot/sites/admissions.uiowa.edu/modules/admissions_migrate/src/Plugin/migrate/source/AreaOfStudy.php
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.install
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/drush.services.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Commands/BrandCoreCommands.php
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Controller/LockupController.php
  docroot/sites/hr.uiowa.edu/modules/hr_core/hr_core.install
  docroot/sites/hr.uiowa.edu/themes/hr/hr.theme
  docroot/sites/ighn.international.uiowa.edu/modules/ighn_core/ighn_core.module
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/src/Plugin/Block/PalliativeGradMapBlock.php
  docroot/sites/uiowa.edu/modules/uiowa_edu_core/uiowa_edu_core.module
  phpcs.xml
Labels: php, joeing-rogue

#4015 SPPA Private - Follow-up fixes
  config/pharmacy.uiowa.edu/core.entity_view_display.node.person.teaser.yml
  config/pharmacy.uiowa.edu/views.view.palliative_grad.yml
  config/sppa.uiowa.edu/config_split.config_split.sppa_uiowa_edu.yml
  config/sppa.uiowa.edu/core.entity_view_display.node.page.default.yml
  config/sppa.uiowa.edu/user.role.viewer.yml
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/pharmacy_core.module
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/templates/node--person--teaser.html.twig
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/templates/views-view-unformatted--palliative-grad.html.twig
Labels: joeing-rogue

#4020 add tag filter to content overview, moderated content
  config/default/views.view.content.yml
  config/default/views.view.moderated_content.yml
Labels: joeing-rogue
