Repository uiowa/uiowa, pull requests merged in 2021-06, with the labels that each got.

#3622 bulk publishing permissions
  config/admissions.uiowa.edu/config_split.config_split.admissions.yml
  config/admissions.uiowa.edu/user.role.publisher.yml
  config/admissions.uiowa.edu/user.role.webmaster.yml
  config/admissions.uiowa.edu/workflows.workflow.editorial.yml
Labels: admissions.uiowa.edu

#3629 Hotfix for `sitenow_update_9011()`
  docroot/profiles/custom/sitenow/sitenow.install
Labels: bug

#3634 Initialize strategicplan.clas.uiowa.edu multisite on uiowa01
  box/config.yml
  config/strategicplan.clas.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/strategicplan.clas.uiowa.edu/blt.yml
  docroot/sites/strategicplan.clas.uiowa.edu/default.local.drush.yml
  docroot/sites/strategicplan.clas.uiowa.edu/default.settings.php
  docroot/sites/strategicplan.clas.uiowa.edu/settings.php
  docroot/sites/strategicplan.clas.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/strategicplan.clas.uiowa.edu/settings/default.local.settings.php
  drush/sites/classtrategicplan.site.yml
Labels: clas, provision

#3612 Add additional default person types (adjunct, visiting, postdoc, alumni)
  config/default/config_split.config_split.additional_person_types.yml
  config/features/additional_person_types/.htaccess
  config/features/additional_person_types/sitenow_people.person_type.adjunct_faculty.yml
  config/features/additional_person_types/sitenow_people.person_type.alumni.yml
  config/features/additional_person_types/sitenow_people.person_type.postdoc.yml
  config/features/additional_person_types/sitenow_people.person_type.visiting_faculty.yml
Labels: enhancement

#3655 Initialize jaynesresearchgroup.lab.uiowa.edu multisite on uiowa
  box/config.yml
  config/jaynesresearchgroup.lab.uiowa.edu/.gitkeep
  docroot/sites/jaynesresearchgroup.lab.uiowa.edu/blt.yml
  docroot/sites/jaynesresearchgroup.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/jaynesresearchgroup.lab.uiowa.edu/default.settings.php
  docroot/sites/jaynesresearchgroup.lab.uiowa.edu/settings.php
  docroot/sites/jaynesresearchgroup.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/jaynesresearchgroup.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/labjaynesresearchgroup.site.yml
Labels: clas, provision

#3621 Create Panopto media type and update permissions for SiteNow v3.
  config/admissions.uiowa.edu/core.entity_view_display.media.panopto.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.media.panopto.large.yml
  config/admissions.uiowa.edu/core.entity_view_display.media.panopto.media_library.yml
  config/admissions.uiowa.edu/core.entity_view_display.media.panopto.medium.yml
  config/admissions.uiowa.edu/core.entity_view_display.media.panopto.small.yml
  config/admissions.uiowa.edu/user.role.editor.yml
  config/admissions.uiowa.edu/user.role.publisher.yml
  config/admissions.uiowa.edu/user.role.webmaster.yml
  config/default/core.entity_form_display.media.panopto.default.yml
  config/default/core.entity_form_display.media.panopto.media_library.yml
  config/default/core.entity_view_display.media.panopto.default.yml
  config/default/core.entity_view_display.media.panopto.large.yml
  config/default/core.entity_view_display.media.panopto.media_library.yml
  config/default/core.entity_view_display.media.panopto.medium.yml
  config/default/core.entity_view_display.media.panopto.small.yml
  config/default/field.field.media.panopto.field_media_panopto_url.yml
  config/default/field.storage.media.field_media_panopto_url.yml
  config/default/filter.format.filtered_html.yml
  config/default/media.type.panopto.yml
  config/default/user.role.editor.yml
  config/default/user.role.publisher.yml
  config/default/user.role.webmaster.yml
  config/features/apr/user.role.webmaster.yml
  config/features/areas_of_study/user.role.editor.yml
  config/features/areas_of_study/user.role.publisher.yml
  config/features/areas_of_study/user.role.webmaster.yml
  config/features/event/core.entity_form_display.node.event.default.yml
  config/features/event/core.entity_view_display.node.event.default.yml
  config/features/event/core.entity_view_display.node.event.teaser.yml
  config/features/event/core.entity_view_display.node.event.token.yml
  config/features/event/field.field.node.event.field_event_when.yml
  config/features/event/user.role.editor.yml
  config/features/event/user.role.publisher.yml
  config/features/event/user.role.webmaster.yml
  config/features/scholarship/user.role.editor.yml
  config/features/scholarship/user.role.publisher.yml
  config/features/scholarship/user.role.webmaster.yml
  config/grad.uiowa.edu/user.role.editor.yml
  config/grad.uiowa.edu/user.role.webmaster.yml
  config/policy.clas.uiowa.edu/user.role.editor.yml
  config/policy.clas.uiowa.edu/user.role.publisher.yml
  config/policy.clas.uiowa.edu/user.role.webmaster.yml
  config/transportation.uiowa.edu/user.role.webmaster.yml
  config/uiowa.edu/user.role.webmaster.yml
  docroot/modules/custom/sitenow_media_wysiwyg/sitenow_media_wysiwyg.module
  docroot/modules/custom/sitenow_media_wysiwyg/src/Form/PanoptoForm.php
  docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/Field/FieldFormatter/PanoptoUrlFormatter.php
  docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/Field/FieldType/PanoptoUrl.php
  docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/Field/FieldWidget/PanoptoUrlWidget.php
  docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/Validation/Constraint/PanoptoURLConstraint.php
  docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/Validation/Constraint/PanoptoURLConstraintValidator.php
  docroot/modules/custom/sitenow_media_wysiwyg/src/Plugin/media/Source/Panopto.php
  docroot/themes/custom/uids_base/scss/components/sitenow/sitenow_wysiwyg.scss
  docroot/themes/custom/uids_base/scss/components/video/video-utilities.scss
  docroot/themes/custom/uids_base/templates/content/media--panopto.html.twig
  docroot/themes/custom/uids_base/uids_base.info.yml
  docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/media/_embedded-entity.scss
  drush/Commands/UiowaCommands.php
Labels: WIP

#3665 Person Type Status fix
  docroot/modules/custom/sitenow_people/sitenow_people.module
Labels: bug

#3668 Added additional_person_types split to config_ignore.
  config/default/config_ignore.settings.yml
Labels: bug, clas

#3645 Add operator option for person type status to people list block view
  config/default/core.entity_view_display.node.person.default.yml
  config/default/views.view.people_list_block.yml
  docroot/modules/custom/sitenow_people/sitenow_people.module
Labels: grad

#3717 improve media library add tabs spacing
  docroot/modules/custom/sitenow_media_wysiwyg/css/media-overrides.css
Labels: joeing-rogue
