Repository uiowa/uiowa, pull requests merged in 2021-02, with the labels that each got.

#2961 Academic Units fix for saving data
  config/grad.uiowa.edu/field.field.node.mentor.field_uiowa_college.yml
  docroot/modules/custom/uiowa_entities/src/Plugin/Field/FieldFormatter/AcademicUnitsFormatter.php
  docroot/modules/custom/uiowa_entities/src/Plugin/Field/FieldType/AcademicUnits.php
  docroot/modules/custom/uiowa_entities/src/Plugin/Field/FieldWidget/AcademicUnitsWidget.php
Labels: bug, grad.uiowa.edu

#3031 i2895-student-profile-bug
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/views-view-unformatted--student-profiles.html.twig
Labels: admissions.uiowa.edu

#3036 Initialize uimsa.org.uiowa.edu multisite on uiowa02
  box/config.yml
  config/uimsa.org.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/uimsa.org.uiowa.edu/blt.yml
  docroot/sites/uimsa.org.uiowa.edu/default.local.drush.yml
  docroot/sites/uimsa.org.uiowa.edu/default.settings.php
  docroot/sites/uimsa.org.uiowa.edu/settings.php
  docroot/sites/uimsa.org.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/uimsa.org.uiowa.edu/settings/default.local.settings.php
  drush/sites/orguimsa.site.yml
Labels: provision

#3040 Provisions 02/09
  box/config.yml
  config/boes.lab.uiowa.edu/.gitkeep
  config/cheatum.lab.uiowa.edu/.gitkeep
  docroot/sites/boes.lab.uiowa.edu/blt.yml
  docroot/sites/boes.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/boes.lab.uiowa.edu/default.settings.php
  docroot/sites/boes.lab.uiowa.edu/settings.php
  docroot/sites/boes.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/boes.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/cheatum.lab.uiowa.edu/blt.yml
  docroot/sites/cheatum.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/cheatum.lab.uiowa.edu/default.settings.php
  docroot/sites/cheatum.lab.uiowa.edu/settings.php
  docroot/sites/cheatum.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/cheatum.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/labboes.site.yml
  drush/sites/labcheatum.site.yml
Labels: provision

#3065 Override 9.1 Claro node form style
  docroot/modules/custom/uiowa_core/css/claro-node-form.css
  docroot/modules/custom/uiowa_core/uiowa_core.libraries.yml
  docroot/modules/custom/uiowa_core/uiowa_core.module
Labels: bug

#3070 Hotfix more lb styles
  docroot/modules/custom/layout_builder_custom/src/EventSubscriber/SectionComponentSubscriber.php
  docroot/modules/custom/sitenow_events/sitenow_events.module
  docroot/modules/custom/uiowa_aggregator/uiowa_aggregator.module
  docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-hero.html.twig
Labels: bug

#3082 Re-ordered repositories and patches
  composer.json
  composer.lock
Labels: DX

#3096 i3077 - Made featured image required for aos and added to config split
  config/admissions.uiowa.edu/config_split.config_split.admissions.yml
  config/admissions.uiowa.edu/field.field.node.area_of_study.field_image.yml
Labels: admissions.uiowa.edu, joeing-rogue

#3109 Hotfix HR media
  docroot/sites/hr.uiowa.edu/themes/hr/hr.info.yml
  docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/media/_embedded-entity.scss
  docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/media/_media--type-image.scss
Labels: bug

#3111 HR Video - fix default and full size, fix ckeditor versions
  docroot/themes/custom/uiowa_bootstrap/scss/partials/03_components/media/_embedded-entity.scss
Labels: bug

#3113 Toggle Navigation Alignment
  docroot/themes/custom/uids_base/scss/components/search-toggle.scss
Labels: bug

#3128 SROP scholar image Display
  config/grad.uiowa.edu/core.entity_view_display.node.scholar.teaser.yml
Labels: bug, grad.uiowa.edu
