Repository uiowa/uiowa, pull requests merged in 2021-12, with the labels that each got.

#4524 Set unique hash salt for each multisite.
  blt/src/Blt/Plugin/Commands/ReplaceCommands.php
  docroot/sites/settings/global.settings.php
  salt.txt
  tests/phpunit/src/Unit/FilesystemTest.php
Labels: requires cache rebuild

#4532 Admissions - Student Profiles Grid Filtering Fix
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.student_profile.default.yml
  config/sites/admissions.uiowa.edu/views.view.student_card.yml
Labels: gone rogue

#4581 Hotfix - Rollback SharedTempstore solution
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
Labels: bug

#4576 Hotfix: change ddev webserver to apache.
  .ddev/config.yaml
Labels: gone rogue

#4590 Hotfix - Null check on region items before block render
  docroot/modules/custom/uiowa_core/src/Plugin/Block/RegionContentBlock.php
  docroot/modules/custom/uiowa_core/tests/src/Unit/RegionContentBlockTest.php
Labels: bug

#4588 Views Pager ID Bug - use cache instead of tempstore
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.services.yml
Labels: bug, gone rogue

#4598 Fix ReplicatorEvents error
  docroot/modules/custom/layout_builder_custom/src/EventSubscriber/ReplicateSubscriber.php
Labels: gone rogue
