Repository uiowa/uiowa, pull requests merged in 2021-04, with the labels that each got.

#3245 Feature: Update lb_direct_add module and related styles.
  composer.json
  composer.lock
  config/default/lb_direct_add.settings.yml
  docroot/themes/custom/uids_base/scss/admin.scss
Labels: joeing-rogue, layout builder, ux

#3346 Set bot crawl-delay and unset internal pages from HTML head.
  config/default/robotstxt.settings.yml
  docroot/modules/custom/sitenow_seo/sitenow_seo.module
Labels: config update, joeing-rogue

#3349 Feature: added fix for lb_direct_add `top:100%` issue
  docroot/themes/custom/uids_base/scss/admin.scss
Labels: 1 point, bug

#3363 Force HTTPS locally and document local certificate install.
  box/certs/.gitignore
  box/certs/README.md
  docroot/.htaccess
  patches/core_htaccess.patch
  tests/behat/README.md
  tests/behat/behat.yml
Labels: 3 points, DX, joeing-rogue

#3386 Remove temporary socialwork htaccess redirect from new domain to old domain
  docroot/.htaccess
Labels: clas

#3384 i3348 APR style adjustments
  docroot/modules/custom/uiowa_apr/sass/styles.scss
Labels: 3 points, APR, pharmacy.uiowa.edu
