Repository uiowa/uiowa, pull requests merged in 2021-05, with the labels that each got.

#3452 Provision iowasummerwritingfestival.uiowa.edu multisite on uiowa01
  box/config.yml
  config/iowasummerwritingfestival.uiowa.edu/.gitkeep
  docroot/sites/iowasummerwritingfestival.uiowa.edu/blt.yml
  docroot/sites/iowasummerwritingfestival.uiowa.edu/default.local.drush.yml
  docroot/sites/iowasummerwritingfestival.uiowa.edu/default.settings.php
  docroot/sites/iowasummerwritingfestival.uiowa.edu/settings.php
  docroot/sites/iowasummerwritingfestival.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/iowasummerwritingfestival.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/iowasummerwritingfestival.site.yml
Labels: provision

#3448 Update hook to fix `table` classes
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/scss/components/tables.scss
Labels: hotfix

#3471 Alphabetically sort person type options
  docroot/modules/custom/sitenow_people/sitenow_people.module
Labels: joeing-rogue

#3256 Config README updates
  config/README.md
Labels: docs

#3483 Schema.org Event Date iso-8601 format
  config/features/event/metatag.metatag_defaults.node__event.yml
Labels: joeing-rogue

#3407 Migration computer science
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/config/split/.htaccess
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/config/split/config_split.config_split.cs_migrate.yml
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/config/split/migrate_drupal.settings.yml
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/config/split/migrate_plus.migration.cs_article_redirects.yml
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/config/split/migrate_plus.migration.cs_articles.yml
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/cs_migrate.info.yml
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/cs_migrate.install
  docroot/sites/cs.uiowa.edu/modules/cs_migrate/src/Plugin/migrate/source/Articles.php
Labels: content migration

#2702 Views block display block options for building lists
  composer.json
  composer.lock
  config/default/core.entity_view_display.node.page.default.yml
  config/default/layout_builder_styles.style.card_media_position_left.yml
  config/default/layout_builder_styles.style.card_media_position_right.yml
  config/default/layout_builder_styles.style.card_media_position_stacked.yml
  config/default/views.view.people_list_block.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php
  docroot/modules/custom/sitenow_people/sitenow_people.module
  docroot/modules/custom/sitenow_people/src/Form/SettingsForm.php
  docroot/themes/custom/uids_base/scss/global.scss
  docroot/themes/custom/uids_base/templates/views/views-view-unformatted--list-card.html.twig
  docroot/themes/custom/uids_base/uids_base.theme
Labels: 8 points, joeing-rogue

#3500 Update Area of Study and Transfer tip long text fields to `filtered_html`.
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.install
Labels: admissions.uiowa.edu

#3511 Add style options to people list block
  config/default/layout_builder_styles.style.block_background_style_black.yml
  config/default/layout_builder_styles.style.block_background_style_gold.yml
  config/default/layout_builder_styles.style.block_background_style_gray.yml
  config/default/layout_builder_styles.style.block_background_style_light.yml
  config/default/layout_builder_styles.style.block_card_style_border.yml
  config/default/layout_builder_styles.style.block_grid_threecol_33_34_33.yml
  config/default/layout_builder_styles.style.block_grid_twocol_50_50.yml
  config/default/layout_builder_styles.style.block_hide_descriptions.yml
  config/default/layout_builder_styles.style.block_hide_details.yml
  config/default/layout_builder_styles.style.block_hide_images.yml
  config/default/layout_builder_styles.style.card_image_large.yml
  config/default/layout_builder_styles.style.card_image_medium.yml
  config/default/layout_builder_styles.style.card_image_small.yml
  config/default/layout_builder_styles.style.content_alignment_center.yml
  config/default/layout_builder_styles.style.content_alignment_left.yml
  config/default/layout_builder_styles.style.list_format_grid.yml
  config/default/layout_builder_styles.style.list_format_list.yml
  config/default/layout_builder_styles.style.media_format_circle.yml
  config/default/layout_builder_styles.style.media_format_square.yml
  config/default/layout_builder_styles.style.media_format_widescreen.yml
  config/default/views.view.people_list_block.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php
  docroot/modules/custom/sitenow_people/sitenow_people.module
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.install
  docroot/themes/custom/uids_base/templates/block/block.html.twig
  docroot/themes/custom/uids_base/templates/content/node--view--taxonomy-term.html.twig
  docroot/themes/custom/uids_base/templates/views/views-view-unformatted--list-card.html.twig
  docroot/themes/custom/uids_base/uids_base.theme
Labels: config update, database update

#3532 Initialize obermann.uiowa.edu multisite on uiowa01
  box/config.yml
  config/obermann.uiowa.edu/.gitkeep
  docroot/sites/obermann.uiowa.edu/blt.yml
  docroot/sites/obermann.uiowa.edu/default.local.drush.yml
  docroot/sites/obermann.uiowa.edu/default.settings.php
  docroot/sites/obermann.uiowa.edu/settings.php
  docroot/sites/obermann.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/obermann.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/obermann.site.yml
Labels: SSL

#3531 Updated layout_builder_shortcuts module to 1.0.0 release.
  composer.json
  composer.lock
Labels: dependencies, layout builder

#3536 Provisions 2021-05-18
  box/config.yml
  config/endingviolence.uiowa.edu/.gitkeep
  config/executive.jobs.uiowa.edu/.gitkeep
  config/legal.studentlife.uiowa.edu/.gitkeep
  config/parents.uiowa.edu/.gitkeep
  config/speakout.uiowa.edu/.gitkeep
  config/youth.dance.uiowa.edu/.gitkeep
  docroot/sites/endingviolence.uiowa.edu/blt.yml
  docroot/sites/endingviolence.uiowa.edu/default.local.drush.yml
  docroot/sites/endingviolence.uiowa.edu/default.settings.php
  docroot/sites/endingviolence.uiowa.edu/settings.php
  docroot/sites/endingviolence.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/endingviolence.uiowa.edu/settings/default.local.settings.php
  docroot/sites/executive.jobs.uiowa.edu/blt.yml
  docroot/sites/executive.jobs.uiowa.edu/default.local.drush.yml
  docroot/sites/executive.jobs.uiowa.edu/default.settings.php
  docroot/sites/executive.jobs.uiowa.edu/settings.php
  docroot/sites/executive.jobs.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/executive.jobs.uiowa.edu/settings/default.local.settings.php
  docroot/sites/legal.studentlife.uiowa.edu/blt.yml
  docroot/sites/legal.studentlife.uiowa.edu/default.local.drush.yml
  docroot/sites/legal.studentlife.uiowa.edu/default.settings.php
  docroot/sites/legal.studentlife.uiowa.edu/settings.php
  docroot/sites/legal.studentlife.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/legal.studentlife.uiowa.edu/settings/default.local.settings.php
  docroot/sites/parents.uiowa.edu/blt.yml
  docroot/sites/parents.uiowa.edu/default.local.drush.yml
  docroot/sites/parents.uiowa.edu/default.settings.php
  docroot/sites/parents.uiowa.edu/settings.php
  docroot/sites/parents.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/parents.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  docroot/sites/speakout.uiowa.edu/blt.yml
  docroot/sites/speakout.uiowa.edu/default.local.drush.yml
  docroot/sites/speakout.uiowa.edu/default.settings.php
  docroot/sites/speakout.uiowa.edu/settings.php
  docroot/sites/speakout.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/speakout.uiowa.edu/settings/default.local.settings.php
  docroot/sites/youth.dance.uiowa.edu/blt.yml
  docroot/sites/youth.dance.uiowa.edu/default.local.drush.yml
  docroot/sites/youth.dance.uiowa.edu/default.settings.php
  docroot/sites/youth.dance.uiowa.edu/settings.php
  docroot/sites/youth.dance.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/youth.dance.uiowa.edu/settings/default.local.settings.php
  drush/sites/danceyouth.site.yml
  drush/sites/endingviolence.site.yml
  drush/sites/jobsexecutive.site.yml
  drush/sites/parents.site.yml
  drush/sites/speakout.site.yml
  drush/sites/studentlifelegal.site.yml
Labels: provision

#3541 Initialize gsurgres.sites.uiowa.edu multisite on uiowa01
  box/config.yml
  config/gsurgres.sites.uiowa.edu/.gitkeep
  docroot/sites/gsurgres.sites.uiowa.edu/blt.yml
  docroot/sites/gsurgres.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/gsurgres.sites.uiowa.edu/default.settings.php
  docroot/sites/gsurgres.sites.uiowa.edu/settings.php
  docroot/sites/gsurgres.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/gsurgres.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/sitesgsurgres.site.yml
Labels: provision

#3542 Initialize staffcouncil.clas.uiowa.edu multisite on uiowa01
  box/config.yml
  config/staffcouncil.clas.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/staffcouncil.clas.uiowa.edu/blt.yml
  docroot/sites/staffcouncil.clas.uiowa.edu/default.local.drush.yml
  docroot/sites/staffcouncil.clas.uiowa.edu/default.settings.php
  docroot/sites/staffcouncil.clas.uiowa.edu/settings.php
  docroot/sites/staffcouncil.clas.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/staffcouncil.clas.uiowa.edu/settings/default.local.settings.php
  drush/sites/classtaffcouncil.site.yml
Labels: provision

#3545 Initialize nejadnik.lab.uiowa.edu multisite on uiowa01
  box/config.yml
  config/nejadnik.lab.uiowa.edu/.gitkeep
  docroot/sites/nejadnik.lab.uiowa.edu/blt.yml
  docroot/sites/nejadnik.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/nejadnik.lab.uiowa.edu/default.settings.php
  docroot/sites/nejadnik.lab.uiowa.edu/settings.php
  docroot/sites/nejadnik.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/nejadnik.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/labnejadnik.site.yml
Labels: provision

#3549 Initialize wkrajewski.iihr.uiowa.edu multisite on uiowa02
  box/config.yml
  config/wkrajewski.iihr.uiowa.edu/.gitkeep
  docroot/sites/sites.php
  docroot/sites/wkrajewski.iihr.uiowa.edu/blt.yml
  docroot/sites/wkrajewski.iihr.uiowa.edu/default.local.drush.yml
  docroot/sites/wkrajewski.iihr.uiowa.edu/default.settings.php
  docroot/sites/wkrajewski.iihr.uiowa.edu/settings.php
  docroot/sites/wkrajewski.iihr.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/wkrajewski.iihr.uiowa.edu/settings/default.local.settings.php
  drush/sites/iihrwkrajewski.site.yml
Labels: provision

#3554 Initialize howes.lab.uiowa.edu multisite on uiowa01
  box/config.yml
  config/howes.lab.uiowa.edu/.gitkeep
  docroot/sites/howes.lab.uiowa.edu/blt.yml
  docroot/sites/howes.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/howes.lab.uiowa.edu/default.settings.php
  docroot/sites/howes.lab.uiowa.edu/settings.php
  docroot/sites/howes.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/howes.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/labhowes.site.yml
Labels: provision

#3556 FontAwesome Role Presentation
  config/default/filter.format.filtered_html.yml
  config/default/filter.format.full_html.yml
  config/default/filter.format.minimal.yml
  config/default/filter.format.plain_text.yml
  docroot/modules/custom/grad_custom/grad_student_profile/templates/field--node--field-person-distinction--student-profile--card.html.twig
  docroot/modules/custom/grad_custom/grad_student_profile/templates/field--node--field-person-distinction--student-profile--default.html.twig
  docroot/modules/custom/grad_custom/grad_student_profile/templates/field--node--field-person-distinction--student-profile--teaser.html.twig
  docroot/modules/custom/grad_custom/grad_student_profile/templates/views-view-unformatted--student-profile-card.html.twig
  docroot/modules/custom/uiowa_core/src/Plugin/Filter/FilterIcon.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/profiles/custom/sitenow/sitenow.profile
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/admissions_core.module
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/field--node--field-person-hometown--student-profile.html.twig
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/field--node--field-student-profile-major--student-profile.html.twig
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/field--node--field-transfer-tips-aos--transfer-tips.html.twig
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/paragraph--admissions-requirement--default.html.twig
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/views-view-unformatted--counselors.html.twig
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/views-view-unformatted--student-profiles.html.twig
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/js/lockup-preview.behaviors.js
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/field--node--field-person-email.html.twig
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/field--node--field-person-phone.html.twig
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/field--node--field-thesis-defense-date.html.twig
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/field--node--field-thesis-defense-location.html.twig
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/field--node--field-uiowa-college.html.twig
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/node--mentor--teaser.html.twig
  docroot/sites/grad.uiowa.edu/modules/grad_core/templates/node--thesis-defense--teaser.html.twig
  docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-cta.html.twig
  docroot/themes/custom/uids_base/templates/block/content-templates/block-content--uiowa-cta.html.twig
  docroot/themes/custom/uids_base/templates/content/aggregator-item.html.twig
  docroot/themes/custom/uids_base/templates/content/node--event--teaser.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-event-location--event--default.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-event-virtual--event--default.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-event-when--event--default.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-person-email.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-person-phone.html.twig
  docroot/themes/custom/uids_base/templates/misc/fontawesomeicon.html.twig
  docroot/themes/custom/uids_base/templates/misc/sitenow-events-single-event.html.twig
  docroot/themes/custom/uids_base/templates/misc/sitenow-events-teaser.html.twig
  docroot/themes/custom/uids_base/templates/paragraphs/accordion/paragraph--accordion-item--default.html.twig
  docroot/themes/custom/uids_base/templates/uids/accordion-item.html.twig
  docroot/themes/custom/uids_base/templates/uids/banner.html.twig
  docroot/themes/custom/uids_base/templates/uids/card.html.twig
  docroot/themes/custom/uids_base/templates/uids/slider--slide.html.twig
  docroot/themes/custom/uids_base/templates/views/views-view-unformatted--list-card.html.twig
  docroot/themes/custom/uids_base/templates/views/views-view-unformatted--person-card.html.twig
Labels: a11y

#3565 Hotfix: Reverting some LB style changes that happened too early.
  config/default/layout_builder_styles.style.block_grid_threecol_33_34_33.yml
  config/default/layout_builder_styles.style.block_grid_twocol_50_50.yml
  config/default/layout_builder_styles.style.block_hide_descriptions.yml
  config/default/layout_builder_styles.style.block_hide_details.yml
  config/default/layout_builder_styles.style.block_hide_images.yml
  config/default/layout_builder_styles.style.list_format_grid.yml
  config/default/layout_builder_styles.style.list_format_list.yml
Labels: hotfix

#3530 Update hook to convert people custom blocks to people list blocks
  config/default/views.view.people_list_block.yml
  docroot/profiles/custom/sitenow/sitenow.install
Labels: SiteNow v3

#3578 Made degree abbreviation not a required field
  config/features/areas_of_study/field.field.paragraph.degree.field_degree_abbreviation.yml
Labels: admissions.uiowa.edu
