Repository uiowa/uiowa, pull requests merged in 2021-03, with the labels that each got.

#3174 Update Webform module to 6.0.2
  composer.lock
  config/default/webform.webform.contact.yml
Labels: security

#3177 Provision two more CLAS sites and two more other sites.
  box/config.yml
  config/cs.uiowa.edu/.gitkeep
  config/frrbp.medicine.uiowa.edu/.gitkeep
  config/physics.uiowa.edu/.gitkeep
  config/scholardev.sites.uiowa.edu/.gitkeep
  docroot/sites/cs.uiowa.edu/blt.yml
  docroot/sites/cs.uiowa.edu/default.local.drush.yml
  docroot/sites/cs.uiowa.edu/default.settings.php
  docroot/sites/cs.uiowa.edu/settings.php
  docroot/sites/cs.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/cs.uiowa.edu/settings/default.local.settings.php
  docroot/sites/frrbp.medicine.uiowa.edu/blt.yml
  docroot/sites/frrbp.medicine.uiowa.edu/default.local.drush.yml
  docroot/sites/frrbp.medicine.uiowa.edu/default.settings.php
  docroot/sites/frrbp.medicine.uiowa.edu/settings.php
  docroot/sites/frrbp.medicine.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/frrbp.medicine.uiowa.edu/settings/default.local.settings.php
  docroot/sites/physics.uiowa.edu/blt.yml
  docroot/sites/physics.uiowa.edu/default.local.drush.yml
  docroot/sites/physics.uiowa.edu/default.settings.php
  docroot/sites/physics.uiowa.edu/settings.php
  docroot/sites/physics.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/physics.uiowa.edu/settings/default.local.settings.php
  docroot/sites/scholardev.sites.uiowa.edu/blt.yml
  docroot/sites/scholardev.sites.uiowa.edu/default.local.drush.yml
  docroot/sites/scholardev.sites.uiowa.edu/default.settings.php
  docroot/sites/scholardev.sites.uiowa.edu/settings.php
  docroot/sites/scholardev.sites.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/scholardev.sites.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/cs.site.yml
  drush/sites/medicinefrrbp.site.yml
  drush/sites/physics.site.yml
  drush/sites/sitesscholardev.site.yml
Labels: provision

#3178 Set Webform configuration on HTML Editor > Element text format to Filtered HTML
  config/default/webform.settings.yml
Labels: bug, enhancement, theming

#3135 Adjust person list media format
  config/default/core.entity_view_display.node.person.teaser.yml
  docroot/themes/custom/uids_base/scss/blocks/people.scss
  docroot/themes/custom/uids_base/scss/content/person.scss
  docroot/themes/custom/uids_base/scss/paragraphs/_uiowa_paragraphs_background_overrides.scss
  docroot/themes/custom/uids_base/scss/paragraphs/uiowa-paragraphs-lists.scss
  docroot/themes/custom/uids_base/scss/views/view-display-id-people.scss
  docroot/themes/custom/uids_base/templates/content/node--person--teaser.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-person-email.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-person-phone.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-person-position--person--teaser.html.twig
  docroot/themes/custom/uids_base/uids_base.theme
Labels: joeing-rogue, theming, uids_base

#3225 Fix for existing accordions
  docroot/themes/custom/uids_base/uids_base.theme
Labels: bug

#3231 Hotfix: Display table outline by default in WYSIWYG
  docroot/modules/custom/sitenow_media_wysiwyg/js/ckeditor_config.js
  docroot/themes/custom/uids_base/scss/components/sitenow/sitenow_wysiwyg.scss
Labels: bug, ux

#3229 Feature: Add pretty title to Admissions Area of Study content type
  config/admissions.uiowa.edu/config_split.config_split.admissions.yml
  config/admissions.uiowa.edu/core.entity_form_display.node.area_of_study.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.pdf.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.teaser.yml
  config/admissions.uiowa.edu/field.field.node.area_of_study.field_area_of_study_pretty_title.yml
  config/admissions.uiowa.edu/field.storage.node.field_area_of_study_pretty_title.yml
Labels: admissions.uiowa.edu, joeing-rogue, site split

#3250 Admissions SEO settings for custom content types
  config/admissions.uiowa.edu/config_split.config_split.admissions.yml
  config/admissions.uiowa.edu/core.entity_form_display.node.area_of_study.default.yml
  config/admissions.uiowa.edu/core.entity_form_display.node.scholarship.default.yml
  config/admissions.uiowa.edu/core.entity_form_display.node.student_profile.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.pdf.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.teaser.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.scholarship.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.scholarship.teaser.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.student_profile.default.yml
  config/admissions.uiowa.edu/core.entity_view_display.node.student_profile.teaser.yml
  config/admissions.uiowa.edu/field.field.node.area_of_study.field_meta_tags.yml
  config/admissions.uiowa.edu/field.field.node.scholarship.field_meta_tags.yml
  config/admissions.uiowa.edu/field.field.node.student_profile.field_meta_tags.yml
  config/admissions.uiowa.edu/metatag.metatag_defaults.node__area_of_study.yml
  config/admissions.uiowa.edu/metatag.metatag_defaults.node__student_profile.yml
  config/admissions.uiowa.edu/metatag.settings.yml
  config/default/config_split.config_split.scholarship.yml
  config/features/scholarship/core.entity_form_display.node.scholarship.default.yml
  config/features/scholarship/core.entity_view_display.node.scholarship.default.yml
  config/features/scholarship/core.entity_view_display.node.scholarship.teaser.yml
  config/features/scholarship/field.field.node.scholarship.field_meta_tags.yml
  config/features/scholarship/metatag.metatag_defaults.node__scholarship.yml
  config/features/scholarship/metatag.settings.yml
Labels: admissions.uiowa.edu, feature split, site split

#3227 I2748 wysiwyg tables styles
  docroot/themes/custom/uids_base/package.json
  docroot/themes/custom/uids_base/scss/components/tables.scss
Labels: admissions.uiowa.edu

#3269 SiteNow People View Page Filtering
  config/default/views.view.people.yml
  docroot/modules/custom/sitenow_people/sitenow_people.install
  docroot/modules/custom/sitenow_people/sitenow_people.module
  docroot/modules/custom/sitenow_people/src/Form/SettingsForm.php
Labels: config update, database update
