Repository uiowa/uiowa, pull requests merged in 2022-04, with the labels that each got.

#5092 Initialize iywp.org multisite on uiowa02
  docroot/sites/iywp.org/blt.yml
  docroot/sites/iywp.org/default.local.drush.yml
  docroot/sites/iywp.org/default.settings.php
  docroot/sites/iywp.org/settings.php
  docroot/sites/iywp.org/settings/default.includes.settings.php
  docroot/sites/iywp.org/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/org-iywp.site.yml
Labels: clas

#5100 Hotfix: Patch `smart_date` module to fix issues with end date not being set correctly
  composer.json
  composer.lock
Labels: grad, hotfix

#5158 Admissions - Entity Print - Image Block config diff
  config/sites/admissions.uiowa.edu/config_split.patch.core.entity_view_display.block_content.uiowa_image.default.yml
Labels: bug
