Repository uiowa/uiowa, pull requests merged in 2022-10, with the labels that each got.

#5808 Temporary Percy fix
  snapshots.yml
Labels: automation

#5713 Allow page node overrides for regions
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.banner.yml
  config/default/core.entity_view_display.node.page.default.yml
  config/default/core.entity_view_display.node.page.teaser.yml
  config/default/core.entity_view_display.node.page.token.yml
  config/default/field.field.node.page.field_after_content_override.yml
  config/default/field.field.node.page.field_pre_footer_override.yml
  config/default/field.storage.node.field_after_content_override.yml
  config/default/field.storage.node.field_pre_footer_override.yml
  docroot/modules/custom/uiowa_core/src/Form/RegionSettings.php
  docroot/modules/custom/uiowa_core/src/Plugin/Block/RegionContentBlock.php
  docroot/modules/custom/uiowa_core/src/RegionHelper.php
  docroot/modules/custom/uiowa_core/tests/src/Unit/RegionContentBlockTest.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/profiles/custom/sitenow/sitenow.profile
  docroot/themes/custom/uids_base/scss/components/footer.scss
  docroot/themes/custom/uids_base/scss/components/top-scroll.scss
  docroot/themes/custom/uids_base/templates/layout/html.html.twig
Labels: needs scheduled deployment

#5880 update search_api module and update config
  composer.lock
  config/sites/policy.clas.uiowa.edu/views.view.book_search.yml
Labels: clas, database update
