Repository uiowa/uiowa, pull requests merged in 2022-08, with the labels that each got.

#5497 Events block date range
  README.md
  composer.lock
  config/default/config_split.config_split.event.yml
  config/default/config_split.config_split.thesis_defense.yml
  config/default/core.entity_form_display.block_content.uiowa_events.default.yml
  config/default/core.entity_view_display.block_content.uiowa_events.default.yml
  config/default/core.extension.yml
  config/default/field.field.block_content.uiowa_events.field_uiowa_events_date_range.yml
  config/default/field.field.block_content.uiowa_events.field_uiowa_events_sort.yml
  config/default/field.field.block_content.uiowa_events.field_uiowa_events_timeframe.yml
  config/default/field.storage.block_content.field_uiowa_events_date_range.yml
  config/default/field.storage.block_content.field_uiowa_events_sort.yml
  config/default/field.storage.block_content.field_uiowa_events_timeframe.yml
  config/default/smart_date.smart_date_format.compact.yml
  config/default/smart_date.smart_date_format.date_only.yml
  config/default/smart_date.smart_date_format.default.yml
  config/default/smart_date.smart_date_format.time_only.yml
  config/features/event/smart_date.smart_date_format.compact.yml
  config/features/event/smart_date.smart_date_format.date_only.yml
  config/features/event/smart_date.smart_date_format.time_only.yml
  config/features/thesis_defense/smart_date.smart_date_format.default.yml
  config/sites/now.uiowa.edu/config_split.config_split.site.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/sitenow_events/sitenow_events.module
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss
Labels: database update

#5569 Feature: Blockquote field updates with new basic text format
  config/default/core.entity_form_display.block_content.uiowa_quote.default.yml
  config/default/editor.editor.basic.yml
  config/default/field.field.block_content.uiowa_quote.field_uiowa_quote_content.yml
  config/default/field.field.block_content.uiowa_quote.field_uiowa_quote_footer.yml
  config/default/field.storage.block_content.field_uiowa_quote_content.yml
  config/default/field.storage.block_content.field_uiowa_quote_footer.yml
  config/default/filter.format.basic.yml
  config/default/filter.format.full_html.yml
  config/default/filter.format.plain_text.yml
  config/default/user.role.editor.yml
  config/default/user.role.publisher.yml
  config/default/user.role.webmaster.yml
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/package.json
  yarn.lock
Labels: needs_scheduled_deploy

#5603 Initialize alt.clas.uiowa.edu multisite on uiowa01
  docroot/sites/alt.clas.uiowa.edu/blt.yml
  docroot/sites/alt.clas.uiowa.edu/default.local.drush.yml
  docroot/sites/alt.clas.uiowa.edu/default.settings.php
  docroot/sites/alt.clas.uiowa.edu/settings.php
  docroot/sites/alt.clas.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/alt.clas.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/clasalt.site.yml
Labels: clas

#5621 Removing 175 footer logo
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/templates/layout/footer.html.twig
  docroot/themes/custom/uids_base/templates/uids/logo-footer.twig
Labels: needs_scheduled_deploy
