Repository uiowa/uiowa, pull requests merged in 2022-07, with the labels that each got.

#5443 Hotfix - Hours - Account for resourceAlias
  docroot/modules/custom/uiowa_hours/src/HoursApi.php
Labels: bug

#5401 UI Press updates
  composer.lock
  config/sites/uipress.uiowa.edu/views.view.books.yml
  config/sites/uipress.uiowa.edu/views.view.uipress_vocabulary_lists.yml
  docroot/sites/uipress.uiowa.edu/modules/uipress_core/uipress_core.module
Labels: grad

#5452 Temporary hotfix for entity_print + dompdf
  .travis.yml
  composer.json
  composer.lock
Labels: hotfix

#5444 Move LB styles to their own library, override smooth scrolling
  docroot/themes/custom/uids_base/scss/admin.scss
  docroot/themes/custom/uids_base/scss/admin/_toolbar.scss
  docroot/themes/custom/uids_base/scss/layout-builder.scss
  docroot/themes/custom/uids_base/uids_base.libraries.yml
  docroot/themes/custom/uids_base/uids_base.theme
Labels: uids_base, layout builder, uids

#5484 Initialize magidcenter.uiowa.edu multisite on uiowa03
  docroot/sites/magidcenter.uiowa.edu/blt.yml
  docroot/sites/magidcenter.uiowa.edu/default.local.drush.yml
  docroot/sites/magidcenter.uiowa.edu/default.settings.php
  docroot/sites/magidcenter.uiowa.edu/settings.php
  docroot/sites/magidcenter.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/magidcenter.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/magidcenter.site.yml
Labels: clas
