Repository uiowa/uiowa, pull requests merged in 2022-11, with the labels that each got.

#5899 IISC: Pre-launch updates
  config/sites/iisc.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/iisc.uiowa.edu/config_split.patch.user.role.publisher.yml
  config/sites/iisc.uiowa.edu/config_split.patch.user.role.webmaster.yml
  config/sites/iisc.uiowa.edu/core.entity_view_display.node.partner.teaser.yml
  config/sites/iisc.uiowa.edu/views.view.iisc_partners.yml
  config/sites/iisc.uiowa.edu/views.view.iisc_projects.yml
Labels: grad

#5753 Feature print.css for browser printing
  docroot/themes/custom/uids_base/scss/theme/print.scss
Labels: gone rogue

#5914 Initialize productionunit.uiowa.edu multisite on uiowa04
  docroot/sites/productionunit.uiowa.edu/blt.yml
  docroot/sites/productionunit.uiowa.edu/default.local.drush.yml
  docroot/sites/productionunit.uiowa.edu/default.settings.php
  docroot/sites/productionunit.uiowa.edu/settings.php
  docroot/sites/productionunit.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/productionunit.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/productionunit.site.yml
Labels: clas

#5932 hotfixing events classes
  docroot/modules/custom/sitenow_events/sitenow_events.module
Labels: hotfix

#5935 Events block: Include last_day if end_day not present
  docroot/modules/custom/sitenow_events/includes/sitenow_events.teaser.inc
  docroot/modules/custom/sitenow_events/sitenow_events.module
Labels: gone rogue

#5949 Some November dependency updates not handled by dependabot
  README.md
  composer.json
  composer.lock
  docroot/modules/custom/layout_builder_custom/src/Plugin/diff/Field/LayoutSectionFieldBuilder.php
Labels: dependencies

#5950 Update to stable release of easysvg.
  composer.json
  composer.lock
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
Labels: dependencies

#5930 adjust publish_options_allowed_values
  docroot/modules/custom/sitenow_events/sitenow_events.module
  docroot/modules/custom/sitenow_paragraphs/sitenow_paragraphs.module
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/profiles/custom/sitenow/sitenow.profile
Labels: bug, gone rogue, DX

#5953 update readme
  README.md
Labels: docs

#5956 Initialize sociology.uiowa.edu multisite on uiowa04
  docroot/sites/sites.php
  docroot/sites/sociology.uiowa.edu/blt.yml
  docroot/sites/sociology.uiowa.edu/default.local.drush.yml
  docroot/sites/sociology.uiowa.edu/default.settings.php
  docroot/sites/sociology.uiowa.edu/settings.php
  docroot/sites/sociology.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/sociology.uiowa.edu/settings/default.local.settings.php
  drush/sites/sociology.site.yml
Labels: clas
