Repository uiowa/uiowa, pull requests merged in 2022-12, with the labels that each got.

#5934 Facilities named building content type + view
  config/sites/facilities.uiowa.edu/.htaccess
  config/sites/facilities.uiowa.edu/config_split.config_split.site.yml
  config/sites/facilities.uiowa.edu/config_split.patch.metatag.settings.yml
  config/sites/facilities.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/facilities.uiowa.edu/config_split.patch.user.role.publisher.yml
  config/sites/facilities.uiowa.edu/config_split.patch.user.role.viewer.yml
  config/sites/facilities.uiowa.edu/config_split.patch.user.role.webmaster.yml
  config/sites/facilities.uiowa.edu/config_split.patch.workflows.workflow.editorial.yml
  config/sites/facilities.uiowa.edu/core.base_field_override.node.named_building.promote.yml
  config/sites/facilities.uiowa.edu/core.entity_form_display.node.named_building.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.named_building.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.named_building.teaser.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.body.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_additional_info.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_address.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_aerial_view_link.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_building_id.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_honoree_achieve.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_honoree_image.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_honoree_last_name.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_honoree_name.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_honoree_years.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_building_year_built.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_image.yml
  config/sites/facilities.uiowa.edu/field.field.node.named_building.field_meta_tags.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_additional_info.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_address.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_aerial_view_link.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_building_id.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_honoree_achieve.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_honoree_image.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_honoree_last_name.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_honoree_name.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_honoree_years.yml
  config/sites/facilities.uiowa.edu/field.storage.node.field_building_year_built.yml
  config/sites/facilities.uiowa.edu/metatag.metatag_defaults.node__named_building.yml
  config/sites/facilities.uiowa.edu/node.type.named_building.yml
  config/sites/facilities.uiowa.edu/pathauto.pattern.named_building.yml
  config/sites/facilities.uiowa.edu/schemadotorg.schemadotorg_mapping.node.named_building.yml
  config/sites/facilities.uiowa.edu/simple_sitemap.bundle_settings.default.node.named_building.yml
  config/sites/facilities.uiowa.edu/views.view.building_list.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.info.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
  docroot/themes/custom/uids_base/scss/components/form/forms.scss
  docroot/themes/custom/uids_base/scss/views/views.scss
Labels: gone rogue, facilities.uiowa.edu

#6000 uip_classes_allowed_values set cacheable to false
  docroot/modules/custom/sitenow_paragraphs/sitenow_paragraphs.module
Labels: bug

#5925 Create site split for iowasummerwritingfestival.uiowa.edu.
  config/default/config_split.config_split.event.yml
  config/features/event/core.entity_form_display.node.event.default.yml
  config/features/event/core.entity_view_display.node.event.teaser.yml
  config/features/event/views.view.event_details_card.yml
  config/features/event/views.view.event_presenters.yml
  config/features/event/views.view.events.yml
  config/features/event/views.view.events_list_block.yml
  config/sites/admissions.uiowa.edu/config_split.config_split.site.yml
  config/sites/admissions.uiowa.edu/config_split.patch.core.entity_form_display.node.event.default.yml
  config/sites/admissions.uiowa.edu/config_split.patch.metatag.metatag_defaults.node__event.yml
  config/sites/admissions.uiowa.edu/core.entity_form_display.node.event.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.event.default.yml
  config/sites/admissions.uiowa.edu/metatag.metatag_defaults.node__event.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/.htaccess
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.config_split.site.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.core.entity_form_display.node.event.default.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.core.entity_view_display.node.event.teaser.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.core.entity_view_display.node.event.token.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.schemadotorg.schemadotorg_mapping.node.event.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.views.view.events.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/core.entity_view_display.node.event.default.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/field.field.node.event.field_event_genre.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/field.field.node.event.field_event_registration_link.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/field.field.node.event.field_event_type.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/field.storage.node.field_event_genre.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/field.storage.node.field_event_registration_link.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/field.storage.node.field_event_type.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/smart_date.smart_date_format.default_long_date.yml
  docroot/modules/custom/sitenow_events/sitenow_events.module
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/profiles/custom/sitenow/css/admin-overrides.css
  docroot/sites/iowasummerwritingfestival.uiowa.edu/modules/iowasummerwritingfestival_core/iowasummerwritingfestival_core.info.yml
  docroot/sites/iowasummerwritingfestival.uiowa.edu/modules/iowasummerwritingfestival_core/iowasummerwritingfestival_core.module
  docroot/sites/iowasummerwritingfestival.uiowa.edu/modules/iowasummerwritingfestival_core/templates/field--node--field-event-registration-link--event--default.html.twig
  docroot/themes/custom/uids_base/scss/components/card.scss
  docroot/themes/custom/uids_base/scss/components/typography/lists.scss
  docroot/themes/custom/uids_base/scss/content/sitenow-event-single.scss
  docroot/themes/custom/uids_base/scss/views/view-bef.scss
  docroot/themes/custom/uids_base/templates/content/node--event--teaser.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-event-performer--event--teaser.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-event-series-link--event.html.twig
  docroot/themes/custom/uids_base/templates/field/field--node--field-event-when--event--default.html.twig
  docroot/themes/custom/uids_base/templates/uids/card.html.twig
  docroot/themes/custom/uids_base/templates/views/views-view-unformatted--card-list.html.twig
Labels: clas, site split, sitenow_events

#6029 Hand off card meta to the renderer before we pass it through.
  docroot/sites/uipress.uiowa.edu/modules/uipress_core/uipress_core.module
Labels: hotfix

#5961 GCLID/FBCLID workaround
  docroot/profiles/custom/sitenow/js/get_clickid.js
  docroot/profiles/custom/sitenow/sitenow.libraries.yml
  docroot/profiles/custom/sitenow/sitenow.profile
Labels: gone rogue, profdev

#6031 Recent visual bugs fixes
  docroot/themes/custom/uids_base/scss/components/menus/superfish/horizontal-menu.scss
  docroot/themes/custom/uids_base/scss/components/search-results.scss
  docroot/themes/custom/uids_base/scss/components/site-name.scss
  docroot/themes/custom/uids_base/scss/content/person.scss
Labels: gone rogue

#6049 Initialize tech.clas.uiowa.edu multisite on uiowa01
  docroot/sites/sites.php
  docroot/sites/tech.clas.uiowa.edu/blt.yml
  docroot/sites/tech.clas.uiowa.edu/default.local.drush.yml
  docroot/sites/tech.clas.uiowa.edu/default.settings.php
  docroot/sites/tech.clas.uiowa.edu/settings.php
  docroot/sites/tech.clas.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/tech.clas.uiowa.edu/settings/default.local.settings.php
  drush/sites/clastech.site.yml
Labels: clas

#6055 Facilities - a fix for encoded aerial links for button render
  config/sites/facilities.uiowa.edu/views.view.named_buildings.yml
Labels: bug
