Repository uiowa/uiowa, pull requests merged in 2022-03, with the labels that each got.

#4881 Admissions event display permanent fix
  config/sites/admissions.uiowa.edu/config_split.config_split.site.yml
  config/sites/admissions.uiowa.edu/config_split.patch.core.entity_view_display.node.event.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.event.default.yml
Labels: bug, admissions.uiowa.edu

#4873 UIPress authors migration
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/BaseNodeSource.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/config/split/.htaccess
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/config/split/config_split.config_split.uipress_migrate.yml
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/config/split/migrate_drupal.settings.yml
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/config/split/migrate_plus.migration.uipress_author_redirects.yml
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/config/split/migrate_plus.migration.uipress_authors.yml
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/src/Plugin/migrate/source/Authors.php
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/uipress_migrate.info.yml
  docroot/sites/uipress.uiowa.edu/modules/uipress_migrate/uipress_migrate.install
Labels: content migration

#4951 HOTFIX - fixed existing blocks with grid settings
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/profiles/custom/sitenow/sitenow.install
Labels: bug, database update

#4961 Initialize isa.uiowa.edu multisite on uiowa01
  docroot/sites/isa.uiowa.edu/blt.yml
  docroot/sites/isa.uiowa.edu/default.local.drush.yml
  docroot/sites/isa.uiowa.edu/default.settings.php
  docroot/sites/isa.uiowa.edu/settings.php
  docroot/sites/isa.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/isa.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/isa.site.yml
Labels: clas

#4907 Tags added within Relationship text input are hidden from view
  config/default/core.entity_form_display.node.article.default.yml
  config/default/core.entity_form_display.node.page.default.yml
  config/default/core.entity_form_display.node.person.default.yml
  config/default/field.field.node.article.field_tags.yml
  config/default/field.field.node.page.field_tags.yml
  config/default/field.field.node.person.field_tags.yml
Labels: gone rogue

#4920 Create site split for isa.uiowa.edu.
  config/sites/isa.uiowa.edu/.htaccess
  config/sites/isa.uiowa.edu/config_split.config_split.site.yml
  config/sites/isa.uiowa.edu/config_split.patch.core.entity_form_display.node.person.default.yml
  config/sites/isa.uiowa.edu/core.entity_view_display.node.person.default.yml
  config/sites/isa.uiowa.edu/core.entity_view_display.node.person.teaser.yml
  config/sites/isa.uiowa.edu/core.entity_view_display.node.person.token.yml
  config/sites/isa.uiowa.edu/field.field.node.person.field_mentor.yml
  config/sites/isa.uiowa.edu/field.field.node.person.field_program_year.yml
  config/sites/isa.uiowa.edu/field.storage.node.field_mentor.yml
  config/sites/isa.uiowa.edu/field.storage.node.field_program_year.yml
  config/sites/isa.uiowa.edu/sitenow_people.person_type.advisory_board_member.yml
  config/sites/isa.uiowa.edu/sitenow_people.person_type.alumni.yml
  config/sites/isa.uiowa.edu/sitenow_people.person_type.director.yml
  config/sites/isa.uiowa.edu/sitenow_people.person_type.executive_committee_member.yml
  config/sites/isa.uiowa.edu/sitenow_people.person_type.mentor.yml
Labels: clas, site split

#4902 Update dependencies 2022-03
  README.md
  composer.json
  composer.lock
  config/default/user.role.editor.yml
  config/default/user.role.publisher.yml
  config/default/user.role.viewer.yml
  config/default/user.role.webmaster.yml
  docroot/modules/custom/grad_custom/grad_thesis_defense/css/admin.css
  docroot/modules/custom/grad_custom/grad_thesis_defense/grad_thesis_defense.libraries.yml
  docroot/modules/custom/grad_custom/grad_thesis_defense/grad_thesis_defense.module
  docroot/profiles/custom/sitenow/sitenow.install
Labels: database update, requires cache rebuild

#5014 Hotfix - Grad - Fix issues with Thesis Defense date widget
  config/features/thesis_defense/config_split.patch.user.role.publisher.yml
  config/features/thesis_defense/core.entity_form_display.node.thesis_defense.default.yml
  docroot/modules/custom/grad_custom/grad_thesis_defense/css/admin.css
  docroot/modules/custom/grad_custom/grad_thesis_defense/grad_thesis_defense.libraries.yml
  docroot/modules/custom/grad_custom/grad_thesis_defense/grad_thesis_defense.module
Labels: grad

#5015 Body field meta descriptions fix
  config/features/scholarship/metatag.metatag_defaults.node__scholarship.yml
  config/sites/admissions.uiowa.edu/metatag.metatag_defaults.node__area_of_study.yml
  config/sites/admissions.uiowa.edu/metatag.metatag_defaults.node__student_profile.yml
  config/sites/grad.admissions.uiowa.edu/metatag.metatag_defaults.node__area_of_study.yml
Labels: bug

#5051 Hotfix - Fix Grad Thesis Defense with future date
  composer.json
  composer.lock
Labels: bug, grad, hotfix

#5055 adding date updated to PDFs
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/sass/pdf.scss
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/templates/node--area-of-study--pdf.html.twig
Labels: admissions.uiowa.edu
