Repository uiowa/uiowa, pull requests merged in 2022-06, with the labels that each got.

#5281 IISC - Remaining content updates
  composer.json
  composer.lock
  config/sites/iisc.uiowa.edu/config_split.config_split.site.yml
  config/sites/iisc.uiowa.edu/core.entity_form_display.node.project.default.yml
  config/sites/iisc.uiowa.edu/core.entity_form_display.taxonomy_term.colleges_and_departments.default.yml
  config/sites/iisc.uiowa.edu/core.entity_view_display.node.project.default.yml
  config/sites/iisc.uiowa.edu/core.entity_view_display.node.project.teaser.yml
  config/sites/iisc.uiowa.edu/core.entity_view_display.taxonomy_term.colleges_and_departments.default.yml
  config/sites/iisc.uiowa.edu/field.field.node.project.field_academic_year.yml
  config/sites/iisc.uiowa.edu/field.field.taxonomy_term.colleges_and_departments.field_image.yml
  config/sites/iisc.uiowa.edu/field.field.taxonomy_term.colleges_and_departments.field_website.yml
  config/sites/iisc.uiowa.edu/field.storage.node.field_academic_year.yml
  config/sites/iisc.uiowa.edu/field.storage.taxonomy_term.field_image.yml
  config/sites/iisc.uiowa.edu/field.storage.taxonomy_term.field_website.yml
  docroot/modules/custom/sitenow_migrate/README.md
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/CreateMediaTrait.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/process/CreateMediaFromFile.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/process/ExtractSummary.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/BaseNodeSource.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/source/ProcessMediaTrait.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/config/split/migrate_plus.migration.iisc_articles.yml
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/config/split/migrate_plus.migration.iisc_colleges_departments.yml
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/config/split/migrate_plus.migration.iisc_partners.yml
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/config/split/migrate_plus.migration.iisc_people.yml
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/config/split/migrate_plus.migration.iisc_projects.yml
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/config/split/migrate_plus.migration.iisc_tags.yml
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/src/Plugin/migrate/source/Articles.php
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/src/Plugin/migrate/source/Partners.php
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/src/Plugin/migrate/source/People.php
  docroot/sites/iisc.uiowa.edu/modules/iisc_migrate/src/Plugin/migrate/source/Projects.php
Labels: blocked

#5343 Update acquia_connector module to 4.x version
  composer.json
  composer.lock
Labels: database update, requires cache rebuild

#5348 Initialize template.clas.uiowa.edu multisite on uiowa01
  docroot/sites/sites.php
  docroot/sites/template.clas.uiowa.edu/blt.yml
  docroot/sites/template.clas.uiowa.edu/default.local.drush.yml
  docroot/sites/template.clas.uiowa.edu/default.settings.php
  docroot/sites/template.clas.uiowa.edu/settings.php
  docroot/sites/template.clas.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/template.clas.uiowa.edu/settings/default.local.settings.php
  drush/sites/clastemplate.site.yml
Labels: clas, default content

#5356 Webform/Honeypot Updates
  composer.json
  composer.lock
  config/default/webform.settings.yml
  docroot/profiles/custom/sitenow/sitenow.profile
Labels: database update

#5381 RSS - GUID fix
  config/default/views.view.articles.yml
  config/default/views.view.taxonomy_term.yml
  docroot/modules/custom/sitenow_articles/sitenow_articles.install
Labels: bug, gone rogue

#5363 Switch from sitenow_find_text to drupal/find_text
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/default/find_text.settings.yml
  config/default/user.role.webmaster.yml
  docroot/modules/custom/sitenow_find_text/sitenow_find_text.module
  docroot/modules/custom/sitenow_find_text/tests/src/Functional/FindTextAjaxTest.php
  docroot/profiles/custom/sitenow/sitenow.install
Labels: sitenow_find_text

#5388 Removed iowasuperfund and students.tippie site splits
  config/sites/iowasuperfund.uiowa.edu/.htaccess
  config/sites/iowasuperfund.uiowa.edu/config_split.config_split.site.yml
  config/sites/iowasuperfund.uiowa.edu/core.base_field_override.node.project_core.promote.yml
  config/sites/iowasuperfund.uiowa.edu/core.base_field_override.node.publication.promote.yml
  config/sites/iowasuperfund.uiowa.edu/core.base_field_override.node.research_project.promote.yml
  config/sites/iowasuperfund.uiowa.edu/core.base_field_override.node.support_core.promote.yml
  config/sites/iowasuperfund.uiowa.edu/core.base_field_override.node.support_core.title.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_form_display.fragment.publication.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_form_display.node.project_core.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_form_display.node.publication.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_form_display.node.research_project.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_form_display.node.support_core.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.fragment.publication.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.project_core.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.project_core.teaser.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.publication.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.publication.teaser.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.research_project.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.research_project.teaser.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.support_core.default.yml
  config/sites/iowasuperfund.uiowa.edu/core.entity_view_display.node.support_core.teaser.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.fragment.publication.field_authors.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.project_core.body.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.publication.field_publication_date.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.publication.field_publication_name.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.publication.field_publication_project_core.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.publication.field_publication_source_link.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.research_project.body.yml
  config/sites/iowasuperfund.uiowa.edu/field.field.node.support_core.body.yml
  config/sites/iowasuperfund.uiowa.edu/field.storage.fragment.field_authors.yml
  config/sites/iowasuperfund.uiowa.edu/field.storage.node.field_publication_date.yml
  config/sites/iowasuperfund.uiowa.edu/field.storage.node.field_publication_name.yml
  config/sites/iowasuperfund.uiowa.edu/field.storage.node.field_publication_project_core.yml
  config/sites/iowasuperfund.uiowa.edu/field.storage.node.field_publication_source_link.yml
  config/sites/iowasuperfund.uiowa.edu/fragments.fragment_type.publication.yml
  config/sites/iowasuperfund.uiowa.edu/node.type.project_core.yml
  config/sites/iowasuperfund.uiowa.edu/node.type.publication.yml
  config/sites/iowasuperfund.uiowa.edu/node.type.research_project.yml
  config/sites/iowasuperfund.uiowa.edu/node.type.support_core.yml
  config/sites/iowasuperfund.uiowa.edu/simple_sitemap.bundle_settings.default.node.project_core.yml
  config/sites/iowasuperfund.uiowa.edu/simple_sitemap.bundle_settings.default.node.research_project.yml
  config/sites/iowasuperfund.uiowa.edu/simple_sitemap.bundle_settings.default.node.support_core.yml
  config/sites/students.tippie.uiowa.edu/.htaccess
  config/sites/students.tippie.uiowa.edu/config_split.config_split.site.yml
  config/sites/students.tippie.uiowa.edu/config_split.patch.robotstxt.settings.yml
Labels: grad
