Repository uiowa/uiowa, pull requests merged in 2023-02, with the labels that each got.

#6168 hotfix - person type statuses
  docroot/modules/custom/sitenow_people/sitenow_people.module
Labels: bug

#6172 Ignore development.services.yml
  .gitignore
  blt/src/Blt/Plugin/Commands/UpdateCommands.php
  docroot/sites/development.services.yml
Labels: DX

#6186 Sprint 149 site updates
  docroot/sites/environmentalsymposium2023.conference.uiowa.edu/blt.yml
  docroot/sites/environmentalsymposium2023.conference.uiowa.edu/default.local.drush.yml
  docroot/sites/environmentalsymposium2023.conference.uiowa.edu/default.settings.php
  docroot/sites/environmentalsymposium2023.conference.uiowa.edu/settings.php
  docroot/sites/environmentalsymposium2023.conference.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/environmentalsymposium2023.conference.uiowa.edu/settings/default.local.settings.php
  docroot/sites/irrc.education.uiowa.edu/blt.yml
  docroot/sites/irrc.education.uiowa.edu/default.local.drush.yml
  docroot/sites/irrc.education.uiowa.edu/default.settings.php
  docroot/sites/irrc.education.uiowa.edu/settings.php
  docroot/sites/irrc.education.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/irrc.education.uiowa.edu/settings/default.local.settings.php
  docroot/sites/nads.uiowa.edu/blt.yml
  docroot/sites/sites.php
  drush/sites/conferenceenvironmentalsymposium2023.site.yml
  drush/sites/educationirrc.site.yml
  drush/sites/nads.site.yml
Labels: deprovision

#6198 UIowa Hours - Change js local date creation
  docroot/modules/custom/uiowa_hours/js/filter_form.js
Labels: bug

#6151 Acquia Connector - update config post-update
  config/default/acquia_connector.settings.yml
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/profiles/custom/sitenow/sitenow.services.yml
  docroot/profiles/custom/sitenow/src/ConfigOverride/AcquiaConnectorOverride.php
  docroot/profiles/custom/sitenow/tests/Unit/AcquiaConnectorOverrideTest.php
Labels: database update, needs scheduled deployment

#6209 Timeline Bug
  docroot/themes/custom/uids_base/scss/components/timeline.scss
Labels: Just do it

#6210 Grad - Added missing program entries manually
  docroot/modules/custom/grad_custom/grad_custom.module
Labels: grad
