Repository uiowa/uiowa, pull requests merged in 2023-11, with the labels that each got.

#7063 Removed duplicate (default) part of button style label
  config/default/layout_builder_styles.style.button_medium.yml
Labels: layout builder

#7071 Add label for reason for closure
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.alert.default.yml
Labels: facilities.uiowa.edu, Just do it

#7087 Hotfixes: Listblock pager offset values and CSHS once regression
  README.md
  composer.json
  composer.lock
  docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php
  docroot/profiles/custom/sitenow/sitenow.install
  patches/3347581.patch
Labels: hotfix

#7096 [Bug] Fix for menu_block spacing
  docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss
Labels: Just do it

#7124 hotfix - classrooms - remove unnecessary access check that causes failure
  docroot/modules/custom/ccom_migrate/src/Plugin/migrate/source/CcomArticle.php
  docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/src/RoomItemProcessor.php
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
Labels: bug
