Repository uiowa/uiowa, pull requests merged in 2023-07, with the labels that each got.

#6664 [ Admissions ] Change view to not use title of 2+2 page.
  config/sites/admissions.uiowa.edu/views.view.majors.yml
Labels: Just do it

#6526 Update drupal core dependencies to 9.5
  .gitattributes
  composer.json
  composer.lock
  config/features/areas_of_study/config_split.patch.user.role.editor.yml
  config/features/areas_of_study/config_split.patch.user.role.publisher.yml
  config/features/areas_of_study/config_split.patch.user.role.webmaster.yml
  config/features/articles_narrow/core.entity_view_display.node.article.default.yml
  config/features/sitenow_intranet/config_split.patch.user.role.viewer.yml
  config/features/sitenow_v2/core.entity_view_display.node.page.default.yml
  config/features/thesis_defense/core.entity_form_display.node.thesis_defense.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.area_of_study.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.event_series.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.major.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.student_profile.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.taxonomy_term.academic_groups.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.taxonomy_term.colleges.default.yml
  config/sites/classrooms.uiowa.edu/core.entity_view_display.node.room.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.named_building.default.yml
  config/sites/grad.admissions.uiowa.edu/core.entity_view_display.node.area_of_study.default.yml
  config/sites/grad.admissions.uiowa.edu/core.entity_view_display.node.costs_estimate.default.yml
  config/sites/grad.admissions.uiowa.edu/core.entity_view_display.node.costs_estimate.teaser.yml
  config/sites/grad.admissions.uiowa.edu/core.entity_view_display.taxonomy_term.colleges.default.yml
  config/sites/housing.uiowa.edu/core.entity_view_display.node.residence_hall.default.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_form_display.node.page.default.yml
  config/sites/hr.uiowa.edu/core.entity_view_display.node.page.default.yml
  config/sites/iisc.uiowa.edu/core.entity_view_display.node.partner.default.yml
  config/sites/iisc.uiowa.edu/core.entity_view_display.node.project.default.yml
  config/sites/uipress.uiowa.edu/core.entity_view_display.node.book.default.yml
  docroot/.ht.router.php
  docroot/.htaccess
  docroot/.htaccess.orig
  docroot/modules/custom/layout_builder_custom/css/layout_builder_custom.overrides.css
  docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.libraries.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/layout_builder_custom/src/LayoutBuilderPreRender.php
  docroot/sites/example.settings.local.php
  docroot/web.config
Labels: WIP, dependencies

#6703 Add a unique ID to sections
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
Labels: P2LB, Just do it

#6711 Formatting fix for `uiowa_core.libraries.yml`
  docroot/modules/custom/uiowa_core/uiowa_core.libraries.yml
Labels: hotfix
