Repository uiowa/uiowa, pull requests merged in 2023-04, with the labels that each got.

#6331 Timeline bugs and fixes
  config/default/core.entity_view_display.paragraph.uiowa_timeline_item.default.yml
  docroot/themes/custom/uids_base/scss/components/timeline.scss
  docroot/themes/custom/uids_base/templates/paragraphs/timeline/paragraph--uiowa-timeline-item.html.twig
  docroot/themes/custom/uids_base/templates/uids/card.html.twig
Labels: layout builder

#5922 Search Block - External URLs
  docroot/modules/custom/uiowa_core/src/Form/SearchBlock.php
  docroot/modules/custom/uiowa_core/src/Plugin/Block/SearchBlock.php
Labels: WIP

#6366 Hours - Closure support
  docroot/modules/custom/uiowa_hours/src/Form/HoursFilterForm.php
  docroot/modules/custom/uiowa_hours/src/Plugin/Block/HoursBlock.php
Labels: gone rogue

#6371 Card headline styles
  config/default/layout_builder_styles.style.banner_gradient_dark.yml
  config/default/layout_builder_styles.style.banner_medium.yml
  config/default/layout_builder_styles.style.button_primary.yml
  config/default/layout_builder_styles.style.card_headline_style_sans_serif.yml
  config/default/layout_builder_styles.style.card_headline_style_serif.yml
  config/default/system.menu.main.yml
  docroot/modules/custom/sitenow_events/sitenow_events.module
  docroot/profiles/custom/sitenow/sitenow.install
Labels: uids_base, layout builder

#6376 Search Block Hotfix
  docroot/modules/custom/uiowa_core/src/Plugin/Block/SearchBlock.php
  docroot/profiles/custom/sitenow/sitenow.install
Labels: bug
