Repository uiowa/uiowa, pull requests merged in 2023-09, with the labels that each got.

#6867 [Bug] Fix for top scroll button size
  docroot/themes/custom/uids_base/scss/components/top-scroll.scss
Labels: Just do it

#6871 [ JDI ] Fix P2LB status column styles.
  docroot/modules/custom/sitenow_p2lb/css/sitenow_p2lb.overrides.css
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
Labels: Just do it

#6870 ITS Services View Block
  config/sites/its.uiowa.edu/config_split.config_split.site.yml
  config/sites/its.uiowa.edu/views.view.services.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
  docroot/sites/its.uiowa.edu/modules/its_core/templates/views-view-summary-unformatted--services.html.twig
  docroot/themes/custom/uids_base/scss/global.scss
Labels: its.uiowa.edu

#6875 [People] Removed comma to avoid comma city
  config/default/core.entity_view_display.node.person.default.yml
  config/features/event/core.entity_view_display.node.person.default.yml
  config/features/grad_person_extended/core.entity_view_display.node.person.default.yml
  config/sites/admissions.uiowa.edu/core.entity_view_display.node.person.default.yml
  config/sites/immuno.grad.uiowa.edu/core.entity_view_display.node.person.default.yml
  config/sites/isa.uiowa.edu/core.entity_view_display.node.person.default.yml
  config/sites/now.uiowa.edu/core.entity_view_display.node.person.default.yml
  config/sites/uipress.uiowa.edu/core.entity_view_display.node.person.default.yml
Labels: Just do it

#6882 [Facilities] Updated label based on feedback.
  config/sites/facilities.uiowa.edu/field.field.node.alert.field_alert_override_building.yml
Labels: Just do it

#6878 [Bug fix] Card block: provide default value for field_uiowa_card_button_display
  docroot/modules/custom/uiowa_core/src/Entity/Card.php
Labels: Just do it

#6869 [CCOM] CCOM logo theme settings
  config/default/uids_base.settings.yml
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/profiles/custom/sitenow/assets/uihc_favicons/android-chrome-192x192.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/android-chrome-256x256.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/android-chrome-512x512.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-114x114.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-120x120.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-144x144.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-152x152.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-180x180.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-57x57.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-60x60.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-72x72.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-76x76.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon-precomposed.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/apple-touch-icon.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/browserconfig.xml
  docroot/profiles/custom/sitenow/assets/uihc_favicons/favicon-16x16.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/favicon-32x32.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/favicon-96x96.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/favicon.ico
  docroot/profiles/custom/sitenow/assets/uihc_favicons/mstile-150x150.png
  docroot/profiles/custom/sitenow/assets/uihc_favicons/safari-pinned-tab.svg
  docroot/profiles/custom/sitenow/assets/uihc_favicons/site.webmanifest
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/assets/images/uihc.png
  docroot/themes/custom/uids_base/scss/components/logo.scss
  docroot/themes/custom/uids_base/templates/layout/footer.html.twig
  docroot/themes/custom/uids_base/templates/layout/header.html.twig
  docroot/themes/custom/uids_base/templates/uids/logo-ccom.twig
  docroot/themes/custom/uids_base/theme-settings.php
  docroot/themes/custom/uids_base/uids_base.theme
Labels: needs scheduled deployment

#6833 Facilities Alert notification scheduling and Dispatch API client updates
  config/sites/facilities.uiowa.edu/config_split.config_split.site.yml
  config/sites/facilities.uiowa.edu/config_split.patch.core.entity_form_display.node.alert.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.alert.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.alert.dispatch.yml
  config/sites/facilities.uiowa.edu/core.entity_view_mode.node.dispatch.yml
  config/sites/facilities.uiowa.edu/facilities_core.settings.yml
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.links.task.yml
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.module
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.permissions.yml
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.routing.yml
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.services.yml
  docroot/modules/custom/sitenow_dispatch/src/Dispatch.php
  docroot/modules/custom/sitenow_dispatch/src/DispatchApiClient.php
  docroot/modules/custom/sitenow_dispatch/src/DispatchApiClientInterface.php
  docroot/modules/custom/sitenow_dispatch/src/Form/SettingsForm.php
  docroot/modules/custom/sitenow_dispatch/src/Form/SubscribeForm.php
  docroot/modules/custom/sitenow_dispatch/src/Form/ThankYouForm.php
  docroot/modules/custom/sitenow_dispatch/src/Form/ThankYouSettingsForm.php
  docroot/modules/custom/sitenow_dispatch/src/Plugin/Block/SignUpFormBlock.php
  docroot/modules/custom/uiowa_core/src/Access/UiowaCoreAccess.php
  docroot/modules/custom/uiowa_core/src/ApiClientBase.php
  docroot/modules/custom/uiowa_core/src/ApiClientInterface.php
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/config/schema/facilities_core.schema.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.info.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.links.menu.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.links.task.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.routing.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Form/NodeAlertDispatchForm.php
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Form/SettingsForm.php
Labels: requires cache rebuild, needs scheduled deployment

#6876 [Bug fix] Button block mobile spacing fix
  docroot/themes/custom/uids_base/scss/components/button.scss
  docroot/themes/custom/uids_base/scss/components/region_item.scss
Labels: Just do it

#6913 [ITS] Service content type permission updates
  config/sites/its.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/its.uiowa.edu/config_split.patch.user.role.publisher.yml
Labels: Just do it

#6888 [ITS] Services reference articles
  config/sites/its.uiowa.edu/config_split.config_split.site.yml
  config/sites/its.uiowa.edu/config_split.patch.core.entity_form_display.node.article.default.yml
  config/sites/its.uiowa.edu/config_split.patch.core.entity_view_display.node.article.teaser.yml
  config/sites/its.uiowa.edu/config_split.patch.core.entity_view_display.node.article.token.yml
  config/sites/its.uiowa.edu/config_split.patch.metatag.settings.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.article.default.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.service.default.yml
  config/sites/its.uiowa.edu/field.field.node.article.field_article_related_service.yml
  config/sites/its.uiowa.edu/field.storage.node.field_article_related_service.yml
  config/sites/its.uiowa.edu/views.view.service_related_articles.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
Labels: its.uiowa.edu

#6906 Dispatch/Facilities Message Logging
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.install
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.module
  docroot/modules/custom/sitenow_dispatch/sitenow_dispatch.services.yml
  docroot/modules/custom/sitenow_dispatch/src/MessageLogRepository.php
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Form/NodeAlertDispatchForm.php
Labels: facilities.uiowa.edu

#6881 [Gallery block] Image gallery block enhancements
  config/default/layout_builder_styles.style.media_format_no_crop.yml
  config/default/layout_builder_styles.style.media_format_square.yml
  config/default/layout_builder_styles.style.media_format_widescreen.yml
  config/sites/housing.uiowa.edu/core.entity_view_display.node.residence_hall.default.yml
  docroot/modules/custom/layout_builder_custom/js/image-block-form.js
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.libraries.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/sitenow_articles/sitenow_articles.module
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/classrooms_core.module
  docroot/sites/housing.uiowa.edu/modules/housing_core/housing_core.module
  docroot/sites/housing.uiowa.edu/modules/housing_core/templates/field--node--field-residence-hall-images--residence-hall--default.html.twig
  docroot/sites/housing.uiowa.edu/modules/housing_core/templates/field--node--field-residence-hall-rr--residence-hall--default.html.twig
  docroot/themes/custom/uids_base/scss/components/grid.scss
  docroot/themes/custom/uids_base/scss/components/image-gallery-block.scss
  docroot/themes/custom/uids_base/scss/fields/fields.scss
  docroot/themes/custom/uids_base/templates/field/field--field-gallery-images.html.twig
Labels: Just do it

#6932 Drupal 10 Contrib Low Hanging Fruit
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/sites/brand.uiowa.edu/workbench_email.workbench_email_template.approved_author.yml
Labels: database update
