Repository uiowa/uiowa, pull requests merged in 2023-10, with the labels that each got.

#6953 Uninstalls the `components` module
  config/default/components.settings.yml
  config/default/core.extension.yml
  docroot/themes/custom/uids_base/uids_base.info.yml
Labels: drupal-10

#6966 Webform d10 from 6.1.3 to 6.2.0-beta6
  composer.json
  composer.lock
  config/default/editor.editor.webform_default.yml
  config/default/filter.format.webform_default.yml
  config/default/webform.settings.yml
  config/default/webform.webform_options.days.yml
  config/default/webform.webform_options.education.yml
  config/default/webform.webform_options.employment_status.yml
  config/default/webform.webform_options.ethnicity.yml
  config/default/webform.webform_options.gender.yml
  config/default/webform.webform_options.industry.yml
  config/default/webform.webform_options.likert_agreement.yml
  config/default/webform.webform_options.likert_comparison.yml
  config/default/webform.webform_options.likert_importance.yml
  config/default/webform.webform_options.likert_quality.yml
  config/default/webform.webform_options.likert_satisfaction.yml
  config/default/webform.webform_options.likert_ten_scale.yml
  config/default/webform.webform_options.likert_would_you.yml
  config/default/webform.webform_options.marital_status.yml
  config/default/webform.webform_options.months.yml
  config/default/webform.webform_options.phone_types.yml
  config/default/webform.webform_options.relationship.yml
  config/default/webform.webform_options.size.yml
  config/default/webform.webform_options.state_codes.yml
  config/default/webform.webform_options.state_names.yml
  config/default/webform.webform_options.state_province_codes.yml
  config/default/webform.webform_options.state_province_names.yml
  config/default/webform.webform_options.titles.yml
  config/default/webform.webform_options.yes_no.yml
Labels: drupal-10

#6975 Uninstall `oembed_providers` module and associated code/config changes
  config/default/core.extension.yml
  config/default/media.type.remote_video.yml
  config/default/oembed_providers.bucket.video.yml
  config/default/oembed_providers.provider.uiowa_kaltura.yml
  config/default/oembed_providers.settings.yml
  docroot/profiles/custom/sitenow/sitenow.install
Labels: dependencies, drupal-10

#6977 Moving to `project/classy` in preparation for D10
  composer.json
  composer.lock
  docroot/themes/custom/uids_base/uids_base.info.yml
Labels: drupal-10

#6983 Hotfix - Webform Email Body Text Format
  config/default/webform.settings.yml
Labels: bug

#6898 Remove embed, entity_embed
  config/default/config_split.config_split.sitenow_v2.yml
  config/default/core.extension.yml
  config/default/embed.button.node.yml
  config/default/embed.settings.yml
  config/default/entity_embed.settings.yml
  config/default/entity_usage.settings.yml
  config/default/filter.format.basic.yml
  config/default/filter.format.filtered_html.yml
  config/default/filter.format.full_html.yml
  config/default/filter.format.minimal.yml
  config/default/filter.format.minimal_plus.yml
  config/default/filter.format.plain_text.yml
  config/default/tour.tour.content-add.yml
  config/default/tour.tour.content-article.yml
  config/default/tour.tour.content-edit.yml
  config/features/sitenow_v2/config_split.patch.core.entity_form_display.node.page.default.yml
  config/features/sitenow_v2/embed.button.media_entity_embed.yml
  docroot/modules/custom/sitenow_media_wysiwyg/sitenow_media_wysiwyg.info.yml
  docroot/modules/custom/sitenow_media_wysiwyg/sitenow_media_wysiwyg.module
  docroot/profiles/custom/sitenow/sitenow.install
Labels: database update

#6996 Updated to D10.0 compatible version of ctools without exposed filters updates
  composer.json
  composer.lock
  config/default/pathauto.pattern.article.yml
  config/default/pathauto.pattern.person.yml
Labels: database update, drupal-10

#7005 Allowed formats
  composer.json
  composer.lock
Labels: drupal-10

#6542 Switch to symfony_mailer
  composer.json
  composer.lock
  config/default/config_split.config_split.dev.yml
  config/default/config_split.config_split.local.yml
  config/default/config_split.config_split.stage.yml
  config/default/core.extension.yml
  config/default/filter.format.email_html.yml
  config/default/symfony_mailer.mailer_policy._.yml
  config/default/symfony_mailer.mailer_policy.symfony_mailer.test.yml
  config/default/symfony_mailer.mailer_policy.user.cancel_confirm.yml
  config/default/symfony_mailer.mailer_policy.user.password_reset.yml
  config/default/symfony_mailer.mailer_policy.user.register_admin_created.yml
  config/default/symfony_mailer.mailer_policy.user.register_no_approval_required.yml
  config/default/symfony_mailer.mailer_policy.user.register_pending_approval.yml
  config/default/symfony_mailer.mailer_policy.user.register_pending_approval_admin.yml
  config/default/symfony_mailer.mailer_policy.user.status_activated.yml
  config/default/symfony_mailer.mailer_policy.user.status_blocked.yml
  config/default/symfony_mailer.mailer_policy.user.status_canceled.yml
  config/default/symfony_mailer.mailer_transport.null.yml
  config/default/symfony_mailer.mailer_transport.sendmail.yml
  config/default/symfony_mailer.mailer_transport.smtp.yml
  config/default/symfony_mailer.settings.yml
  config/envs/dev/config_split.patch.symfony_mailer.settings.yml
  config/envs/dev/reroute_email.settings.yml
  config/envs/local/config_split.patch.symfony_mailer.settings.yml
  config/envs/local/reroute_email.settings.yml
  config/envs/local/symfony_mailer.mailer_policy.update.status_notify.yml
  config/envs/stage/config_split.patch.symfony_mailer.settings.yml
  config/envs/stage/reroute_email.settings.yml
  config/sites/brand.uiowa.edu/config_split.config_split.site.yml
  config/sites/brand.uiowa.edu/config_split.patch.system.mail.yml
  config/sites/brand.uiowa.edu/mailsystem.settings.yml
  config/sites/brand.uiowa.edu/swiftmailer.message.yml
  config/sites/brand.uiowa.edu/swiftmailer.transport.yml
  docroot/modules/custom/uiowa_core/tests/src/Kernel/MailTest.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.install
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
  docroot/sites/brand.uiowa.edu/modules/brand_core/drush.services.yml
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Commands/BrandCoreCommands.php
  docroot/sites/brand.uiowa.edu/modules/brand_core/src/Plugin/EmailBuilder/BrandLockupDigestEmailBuilder.php
  docroot/sites/settings/global.settings.php
Labels: drupal-10

#7009 Update Drush User Commands
  composer.json
  composer.lock
Labels: drupal-10

#7010 Move theme_permission to custom
  composer.json
  composer.lock
  docroot/modules/custom/theme_permission/PATCHES.txt
  docroot/modules/custom/theme_permission/README.txt
  docroot/modules/custom/theme_permission/composer.json
  docroot/modules/custom/theme_permission/src/Controller/AccessController.php
  docroot/modules/custom/theme_permission/src/Routing/RouteSubscriber.php
  docroot/modules/custom/theme_permission/src/ThemePerm.php
  docroot/modules/custom/theme_permission/tests/src/Functional/AccessBlockBrowserTest.php
  docroot/modules/custom/theme_permission/tests/src/Functional/AccessThemeBrowserTest.php
  docroot/modules/custom/theme_permission/tests/src/Functional/ThemePermissionTestBase.php
  docroot/modules/custom/theme_permission/theme_permission.info.yml
  docroot/modules/custom/theme_permission/theme_permission.permissions.yml
  docroot/modules/custom/theme_permission/theme_permission.services.yml
  docroot/profiles/custom/sitenow/sitenow.install
Labels: needs scheduled deployment

#7013 Facilities' alerts template update
  config/features/sitenow_alerts/config_split.patch.metatag.settings.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.alert.default.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/templates/field--node--field-alert-traffic-control-plan--alert--default.html.twig
Labels: facilities.uiowa.edu

#7019 [P2LB] Fix for banner text to not `strip_tags` for all markup
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
Labels: Just do it

#7054 Hotfix: Fix article/people path auto settings.
  docroot/profiles/custom/sitenow/sitenow.install
Labels: hotfix

#7025 P2LB protected node revision updates
  composer.json
  composer.lock
  config/features/p2lb/views.view.content_v3_converter.yml
  docroot/modules/custom/sitenow_p2lb/css/sitenow_p2lb.overrides.css
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
  docroot/modules/custom/sitenow_p2lb/src/P2LbConverter.php
  docroot/modules/custom/sitenow_p2lb/src/P2LbDeleteRevisions.php
  docroot/modules/custom/sitenow_p2lb/src/Plugin/Action/ConvertParagraphsToLayoutBuilder.php
  docroot/themes/custom/uids_base/scss/components/menus/local-tasks.scss
  docroot/themes/custom/uids_base/uids_base.theme
  patches/3201705.patch
Labels: P2LB
