Repository uiowa/uiowa, pull requests merged in 2023-03, with the labels that each got.

#6214 create a patch for development services to add twig debug
  composer.json
  patches/development_services.patch
Labels: gone rogue

#6267 Update storage size for layout section field
  composer.json
  composer.lock
  docroot/profiles/custom/sitenow/sitenow.install
Labels: gone rogue, Just do it

#6273 Minor UI Press update to remove the need for overridden page EVD
  config/sites/uipress.uiowa.edu/config_split.config_split.site.yml
  config/sites/uipress.uiowa.edu/core.entity_view_display.node.page.default.yml
  config/sites/uipress.uiowa.edu/views.view.homepage_books.yml
Labels: grad, DX, Just do it

#6275 Fix for slider headline/apostrophe issue
  docroot/themes/custom/uids_base/templates/paragraphs/paragraph--uiowa-slide.html.twig
  docroot/themes/custom/uids_base/uids_base.theme
Labels: Just do it

#6276 Possible fix to resolve mb_strtolower() error
  docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-banner.html.twig
Labels: Just do it

#6306 Brand - update button on lockup-system view page
  config/sites/brand.uiowa.edu/views.view.lockups.yml
Labels: brand.uiowa.edu, Just do it
