Repository uiowa/uiowa, pull requests merged in 2023-01, with the labels that each got.

#6059 Adjust role mapping configuration
  config/default/config_ignore.settings.yml
  config/sites/brand.uiowa.edu/config_split.config_split.site.yml
  config/sites/brand.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
  config/sites/connect.studentlife.uiowa.edu/.htaccess
  config/sites/connect.studentlife.uiowa.edu/README.md
  config/sites/connect.studentlife.uiowa.edu/config_split.config_split.site.yml
  config/sites/connect.studentlife.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
  config/sites/sitenow.uiowa.edu/config_split.config_split.site.yml
  config/sites/sitenow.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
  config/sites/sppa.uiowa.edu/config_split.config_split.site.yml
  config/sites/sppa.uiowa.edu/config_split.patch.uiowa_auth.settings.yml
  docroot/modules/custom/uiowa_core/src/Commands/UiowaCoreCommands.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/profiles/custom/sitenow/sitenow.install
Labels: database update

#6069 Add a DDEV command for testing update hooks
  .ddev/commands/host/debug-update
  drush/Commands/UiowaCommands.php
  phpcs.xml
Labels: DX

#5756 Updated Antonio local font for better browser consistency
  docroot/themes/custom/uids_base/gulpfile.js
  docroot/themes/custom/uids_base/package.json
  docroot/themes/custom/uids_base/scss/components/button.scss
  docroot/themes/custom/uids_base/scss/components/typography/headings.scss
  docroot/themes/custom/uids_base/scss/global.scss
  yarn.lock
Labels: profdev

#6095 fix default content card blocks
  docroot/profiles/custom/sitenow/content/block_content/3e775397-cb1e-40de-9c53-f00e328edc2d.yml
  docroot/profiles/custom/sitenow/content/block_content/41c43a1b-0473-45b1-b799-2b235c3904fb.yml
  docroot/profiles/custom/sitenow/content/block_content/5026fa65-d6f5-464b-820b-e1cca3ff6be3.yml
  docroot/profiles/custom/sitenow/content/block_content/5294fe6f-aad8-46ab-8b48-f98d11e41818.yml
  docroot/profiles/custom/sitenow/content/block_content/631979b9-cf39-46d2-a357-e8857487fccd.yml
  docroot/profiles/custom/sitenow/content/block_content/81baa7ae-8510-4cec-ad00-c29e95098229.yml
  docroot/profiles/custom/sitenow/content/block_content/e8a1a5d7-a7c6-4b59-a13d-ee498ec7232c.yml
  docroot/profiles/custom/sitenow/sitenow.install
Labels: bug

#6116 Iowa Now: experts list wsod fix
  docroot/sites/now.uiowa.edu/modules/now_core/now_core.module
Labels: bug

#6102 Guest hawkid support (in uiowa_auth)
  composer.lock
Labels: bug

#6123 Update Grad program list
  docroot/modules/custom/grad_custom/grad_custom.module
Labels: grad
