Repository uiowa/uiowa, pull requests merged in 2024-06, with the labels that each got.

#7729 [Dependency updates] Uninstall block_content_template module
  config/default/core.extension.yml
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/scss/global.scss
  docroot/themes/custom/uids_base/templates/block/block--inline-block--featured-content.html.twig
  docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-collection.html.twig
  docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-events.html.twig
  docroot/themes/custom/uids_base/templates/block/content-templates/block-content--featured-content.html.twig
  docroot/themes/custom/uids_base/templates/block/content-templates/block-content--uiowa-collection--accordion.html.twig
  docroot/themes/custom/uids_base/templates/block/content-templates/block-content--uiowa-collection--descriptive-list.html.twig
  docroot/themes/custom/uids_base/templates/block/content-templates/block-content--uiowa-cta.html.twig
  docroot/themes/custom/uids_base/templates/block/content-templates/block-content--uiowa-events.html.twig
  docroot/themes/custom/uids_base/uids_base.theme
Labels: dependencies, requires cache rebuild, needs scheduled deployment

#7758 [Updates] linkit to 6.1.4
  composer.json
  composer.lock
Labels: dependencies

#7760 [Updates] Webform 6.2
  composer.json
  composer.lock
Labels: dependencies

#7766 [Bug] Badge display
  docroot/themes/custom/uids_base/scss/components/badge.scss
Labels: bug, Just do it

#7731 update smart_date to 4.1.3
  composer.json
  composer.lock
  config/default/smart_date.smart_date_format.compact.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.alert.default.yml
  docroot/sites/now.uiowa.edu/modules/now_core/now_core.module
  patches/3409287.patch
  patches/3452796.patch
Labels: database update

#7776 [Bug] Button color contrast fix
  docroot/themes/custom/uids_base/package.json
  yarn.lock
Labels: bug, a11y, Just do it

#7779 [Bug] Contextual edit links fix
  docroot/themes/custom/uids_base/scss/admin.scss
  docroot/themes/custom/uids_base/scss/global.scss
Labels: bug, Just do it

#7782 [Bug] Button `aria-hidden`
  docroot/modules/custom/uiowa_core/uiowa_core.module
Labels: bug, a11y

#7745 [Classrooms] Entity usage stuff
  docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/classrooms_core.install
  docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/src/RoomItemProcessor.php
Labels: needs scheduled deployment

#7786 P2LB - Prevent access to paragraphs widget in new nodes
  config/features/p2lb/field.field.node.page.field_v3_conversion_revision_id.yml
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
  docroot/modules/custom/sitenow_p2lb/src/Controller/P2LbController.php
  docroot/modules/custom/sitenow_p2lb/src/P2LbDeleteRevisions.php
Labels: bug

#7830 [Bug] Added fix for technology icons breaking on classrooms.uiowa.edu
  docroot/themes/custom/uids_base/scss/components/typography/paragraph.scss
Labels: bug, Just do it

#7808 [Bug] List items in WYSIWYG preview
  docroot/themes/custom/uids_base/scss/sitenow_wysiwyg.scss
Labels: bug, Just do it

#7828 [Bug] Menu toggle fix for multiple menu blocks on a page
  docroot/themes/custom/uids_base/assets/js/accessible-menu.init.js
  docroot/themes/custom/uids_base/scss/components/menus/main-menu.scss
  docroot/themes/custom/uids_base/uids_base.theme
Labels: bug, Just do it

#7847 Listblock items per page fixes
  config/sites/emergency.uiowa.edu/config_split.patch.config_ignore.settings.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
Labels: bug

#7841 remove path access on media for non-admins, resolves #4613
  docroot/profiles/custom/sitenow/sitenow.profile
Labels: gone rogue
