Repository uiowa/uiowa, pull requests merged in 2024-01, with the labels that each got.

#7204 [Bug] People list block website field
  config/default/core.entity_view_display.node.person.teaser.yml
  config/default/views.view.people_list_block.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/modules/custom/sitenow_people/src/Entity/Person.php
  docroot/profiles/custom/sitenow/sitenow.install
Labels: bug

#7226 Card-block-form.js machine name updates
  docroot/modules/custom/layout_builder_custom/js/card-block-form.js
Labels: Just do it

#7201 Adding block_margin_default_removed style to all blocks
  config/default/layout_builder_styles.style.block_margin_default_removed.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.artwork.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.named_building.default.yml
  config/sites/facilities.uiowa.edu/core.entity_view_display.node.person.default.yml
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
Labels: bug, Just do it

#7244 DDEV update changes `.ddev/providers/acquia.yaml`
  .ddev/providers/acquia.yaml
Labels: Just do it

#7132 Switch to CKEditor 5
  composer.json
  composer.lock
  config/default/core.extension.yml
  config/default/editor.editor.basic.yml
  config/default/editor.editor.filtered_html.yml
  config/default/editor.editor.full_html.yml
  config/default/editor.editor.minimal.yml
  config/default/editor.editor.minimal_plus.yml
  config/default/editor.editor.webform_default.yml
  config/default/filter.format.basic.yml
  config/default/filter.format.filtered_html.yml
  config/default/filter.format.full_html.yml
  config/default/filter.format.minimal.yml
  config/default/filter.format.minimal_plus.yml
  config/default/fontawesome.settings.yml
  config/sites/facilities.uiowa.edu/config_split.patch.core.entity_form_display.node.alert.default.yml
  config/sites/facilities.uiowa.edu/config_split.patch.core.entity_view_display.node.alert.teaser.yml
  docroot/modules/custom/layout_builder_custom/js/image-block-form.js
  docroot/modules/custom/layout_builder_custom/js/layout_builder_custom.overrides.js
  docroot/modules/custom/sitenow_media_wysiwyg/js/ckeditor_config.js
  docroot/modules/custom/sitenow_media_wysiwyg/sitenow_media_wysiwyg.info.yml
  docroot/modules/custom/sitenow_media_wysiwyg/sitenow_media_wysiwyg.module
  docroot/modules/custom/uiowa_core/src/Plugin/Filter/FilterIcon.php
  docroot/modules/custom/uiowa_core/src/Plugin/Filter/FilterIframe.php
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/profiles/custom/sitenow/sitenow.profile
  docroot/themes/custom/uids_base/assets/images/twitter.png
  docroot/themes/custom/uids_base/package.json
  docroot/themes/custom/uids_base/scss/admin/_off-canvas.scss
  docroot/themes/custom/uids_base/scss/components/card.scss
  docroot/themes/custom/uids_base/scss/components/typography/global-serif.scss
  docroot/themes/custom/uids_base/scss/components/typography/paragraph.scss
  docroot/themes/custom/uids_base/scss/global.scss
  docroot/themes/custom/uids_base/scss/media/media--type-image.scss
  docroot/themes/custom/uids_base/scss/sitenow_wysiwyg.scss
  docroot/themes/custom/uids_base/scss/views/views.scss
  docroot/themes/custom/uids_base/uids_base.info.yml
  patches/14.patch
  patches/3329877.patch
  yarn.lock
Labels: ckeditor
