Repository uiowa/uiowa, pull requests merged in 2024-07, with the labels that each got.

#7881 Hotfix - Views blocks check for exposed input
  docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php
Labels: bug

#7882 Admissions - Fix student profile grid (photo only) paths
  config/sites/admissions.uiowa.edu/views.view.student_card.yml
Labels: bug

#7912 [Registrar] Added css override for label
  docroot/sites/registrar.uiowa.edu/modules/cevalidationsr/cevalidationsr.libraries.yml
  docroot/sites/registrar.uiowa.edu/modules/cevalidationsr/css/cevalidationsr.css
  docroot/sites/registrar.uiowa.edu/modules/cevalidationsr/src/Form/CevalidationsrForm.php
Labels: Just do it

#7924 [Bug] Badge adjustments to fix Safari display issue again
  docroot/themes/custom/uids_base/scss/components/badge.scss
Labels: bug, Just do it
