Repository uiowa/uiowa, pull requests merged in 2024-11, with the labels that each got.

#8216 hotfix - update events_load to include a timeout and error handling
  docroot/modules/custom/sitenow_events/modules/sitenow_events_paragraph/sitenow_events_paragraph.module
  docroot/modules/custom/sitenow_events/sitenow_events.module
Labels: bug

#8248 Tweak logrotate
  logrotate.conf
Labels: bug

#8254 [Bug] Layout builder edit bug
  config/sites/its.uiowa.edu/core.entity_view_display.node.service.default.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.support_article.default.yml
Labels: bug

#8257 Fix filter_iframe schema
  config/default/filter.format.filtered_html.yml
  config/default/filter.format.full_html.yml
  docroot/modules/custom/uiowa_core/config/schema/uiowa_core.schema.yml
  docroot/modules/custom/uiowa_core/src/Plugin/Filter/FilterIframe.php
Labels: bug, gone rogue

#8193 update stage_file_proxy to 3.1.3
  composer.json
  composer.lock
  config/envs/local/stage_file_proxy.settings.yml
Labels: database update, config update, gone rogue
