Repository uiowa/uiowa, pull requests merged in 2024-09, with the labels that each got.

#8031 ITS Updates Sprint 228
  config/sites/its.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/its.uiowa.edu/config_split.patch.user.role.publisher.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
Labels: bug

#8046 [Bug] Event block link fix
  docroot/modules/custom/uiowa_core/src/Entity/Event.php
Labels: bug, Just do it

#8052 [Commencement] Sorting
  config/sites/commencement.uiowa.edu/views.view.ceremonies.yml
Labels: Just do it

#8073 fix uiowa_profiles once implementation
  docroot/modules/custom/uiowa_profiles/js/uiowa-profiles.js
Labels: bug

#8079 [Articles] Pagination bug
  config/default/views.view.article_list_block.yml
  config/default/views.view.articles.yml
  docroot/modules/custom/sitenow_articles/sitenow_articles.install
Labels: bug

#8080 [ Bug ] Fullcalendar: only rebuild if AJAX is from views.
  composer.json
  composer.lock
  patches/fullcalendar_only_rebuild_on_view_change.patch
Labels: bug

#8104 [Registrar] Event display bugs
  docroot/sites/registrar.uiowa.edu/modules/registrar_core/js/academic_calendar.js
  docroot/sites/registrar.uiowa.edu/modules/registrar_core/src/Controller/AcademicCalendarController.php
Labels: bug, registrar.uiowa.edu
