Repository uiowa/uiowa, pull requests merged in 2024-03, with the labels that each got.

#7416 fix the weight warning on ITS alerts
  config/sites/its.uiowa.edu/config_split.patch.core.entity_form_display.node.alert.default.yml
Labels: bug, its.uiowa.edu

#7412 update private_content to 2.1
  composer.json
  composer.lock
Labels: dependencies

#7432 [Facilities] Artwork view updates
  config/sites/facilities.uiowa.edu/views.view.artwork.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
  docroot/themes/custom/uids_base/scss/components/grid.scss
Labels: Just do it

#7422 ITS Alerts Digest Emails
  config/default/smart_date.smart_date_format.compact.yml
  config/sites/its.uiowa.edu/views.view.alerts_list_block.yml
  docroot/sites/its.uiowa.edu/modules/its_core/drush.services.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
  docroot/sites/its.uiowa.edu/modules/its_core/src/Commands/ITSCoreCommands.php
  docroot/sites/its.uiowa.edu/modules/its_core/src/Plugin/EmailBuilder/ITSAlertEmail.php
Labels: its.uiowa.edu

#7421 [ITS] Support article content type
  config/sites/its.uiowa.edu/config_split.config_split.site.yml
  config/sites/its.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/its.uiowa.edu/config_split.patch.user.role.publisher.yml
  config/sites/its.uiowa.edu/config_split.patch.user.role.viewer.yml
  config/sites/its.uiowa.edu/config_split.patch.user.role.webmaster.yml
  config/sites/its.uiowa.edu/config_split.patch.workflows.workflow.editorial.yml
  config/sites/its.uiowa.edu/core.base_field_override.node.support_article.promote.yml
  config/sites/its.uiowa.edu/core.entity_form_display.node.support_article.default.yml
  config/sites/its.uiowa.edu/core.entity_form_display.paragraph.support_article_faqs.default.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.support_article.default.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.support_article.teaser.yml
  config/sites/its.uiowa.edu/core.entity_view_display.paragraph.support_article_faqs.default.yml
  config/sites/its.uiowa.edu/field.field.node.support_article.body.yml
  config/sites/its.uiowa.edu/field.field.node.support_article.field_support_article_category.yml
  config/sites/its.uiowa.edu/field.field.node.support_article.field_support_article_faqs.yml
  config/sites/its.uiowa.edu/field.field.node.support_article.field_support_article_service.yml
  config/sites/its.uiowa.edu/field.field.node.support_article.field_support_article_short_desc.yml
  config/sites/its.uiowa.edu/field.field.paragraph.support_article_faqs.field_support_faqs_answer.yml
  config/sites/its.uiowa.edu/field.field.paragraph.support_article_faqs.field_support_faqs_question.yml
  config/sites/its.uiowa.edu/field.storage.node.field_support_article_category.yml
  config/sites/its.uiowa.edu/field.storage.node.field_support_article_faqs.yml
  config/sites/its.uiowa.edu/field.storage.node.field_support_article_service.yml
  config/sites/its.uiowa.edu/field.storage.node.field_support_article_short_desc.yml
  config/sites/its.uiowa.edu/field.storage.paragraph.field_support_faqs_answer.yml
  config/sites/its.uiowa.edu/field.storage.paragraph.field_support_faqs_question.yml
  config/sites/its.uiowa.edu/metatag.metatag_defaults.node__support_article.yml
  config/sites/its.uiowa.edu/node.type.support_article.yml
  config/sites/its.uiowa.edu/paragraphs.paragraphs_type.support_article_faqs.yml
  config/sites/its.uiowa.edu/pathauto.pattern.support_article.yml
  config/sites/its.uiowa.edu/rabbit_hole.behavior_settings.node_type_support_article.yml
  config/sites/its.uiowa.edu/taxonomy.vocabulary.support_article_categories.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
  docroot/sites/its.uiowa.edu/modules/its_core/templates/field--node--field-support-article-faqs.html.twig
  docroot/sites/its.uiowa.edu/modules/its_core/templates/paragraph--support-article-faqs--default.html.twig
Labels: its.uiowa.edu

#7452 Update Search to use homepage
  docroot/modules/custom/uiowa_search/src/Controller/UiowaSearchResultsController.php
Labels: uiowa.edu

#7478 [Bug] V2 events spacing
  docroot/themes/custom/uids_base/scss/components/event.scss
  docroot/themes/custom/uids_base/templates/paragraphs/paragraph--events--default.html.twig
Labels: bug

#7469 remove apr from codebase
  config/default/config_ignore.settings.yml
  config/default/config_split.config_split.apr.yml
  config/features/apr/.htaccess
  config/features/apr/README.md
  config/features/apr/config_split.patch.user.role.webmaster.yml
  docroot/modules/custom/uiowa_apr/package.json
  docroot/modules/custom/uiowa_apr/sass/styles.scss
  docroot/modules/custom/uiowa_apr/src/Apr.php
  docroot/modules/custom/uiowa_apr/src/Controller/DirectoryController.php
  docroot/modules/custom/uiowa_apr/src/Controller/PublicationsController.php
  docroot/modules/custom/uiowa_apr/src/Controller/SitemapController.php
  docroot/modules/custom/uiowa_apr/src/Form/SettingsForm.php
  docroot/modules/custom/uiowa_apr/src/Routing/AprDynamic.php
  docroot/modules/custom/uiowa_apr/uiowa_apr.info.yml
  docroot/modules/custom/uiowa_apr/uiowa_apr.libraries.yml
  docroot/modules/custom/uiowa_apr/uiowa_apr.links.menu.yml
  docroot/modules/custom/uiowa_apr/uiowa_apr.module
  docroot/modules/custom/uiowa_apr/uiowa_apr.permissions.yml
  docroot/modules/custom/uiowa_apr/uiowa_apr.routing.yml
  docroot/modules/custom/uiowa_apr/uiowa_apr.services.yml
  docroot/themes/custom/uids_base/scss/components/form/forms.scss
Labels: DX

#7480 [ITS] Alert calendar and content type updates
  config/sites/its.uiowa.edu/config_split.patch.field.field.node.alert.field_alert_date.yml
  config/sites/its.uiowa.edu/core.entity_view_display.node.alert.default.yml
  config/sites/its.uiowa.edu/views.view.alerts_list_block.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.libraries.yml
  docroot/sites/its.uiowa.edu/modules/its_core/its_core.module
  docroot/sites/its.uiowa.edu/modules/its_core/js/smartdate-override.js
Labels: its.uiowa.edu

#7496 Remove duplicate page bundle class
  docroot/modules/custom/uiowa_core/src/Entity/Page.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
Labels: bug

#7515 Delete limoli.lab.uiowa.edu multisite on uiowa
  docroot/sites/limoli.lab.uiowa.edu/blt.yml
  docroot/sites/limoli.lab.uiowa.edu/default.local.drush.yml
  docroot/sites/limoli.lab.uiowa.edu/default.settings.php
  docroot/sites/limoli.lab.uiowa.edu/settings.php
  docroot/sites/limoli.lab.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/limoli.lab.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/lablimoli.site.yml
Labels: deprovision
