Repository uiowa/uiowa, pull requests merged in 2024-04, with the labels that each got.

#7527 Fix Moderation Filter
  config/default/views.view.moderated_content.yml
Labels: gone rogue

#7449 Facilities API updates
  composer.json
  composer.lock
  config/sites/facilities.uiowa.edu/config_split.config_split.site.yml
  config/sites/facilities.uiowa.edu/core.entity_form_display.node.building.default.yml
  config/sites/facilities.uiowa.edu/uiowa_facilities.apis.yml
  docroot/modules/custom/sitenow_dispatch/src/DispatchApiClient.php
  docroot/modules/custom/sitenow_dispatch/src/DispatchApiClientInterface.php
  docroot/modules/custom/uiowa_core/src/ApiAuthBasicTrait.php
  docroot/modules/custom/uiowa_core/src/ApiAuthKeyInterface.php
  docroot/modules/custom/uiowa_core/src/ApiAuthKeyTrait.php
  docroot/modules/custom/uiowa_core/src/ApiClientBase.php
  docroot/modules/custom/uiowa_core/src/ApiClientInterface.php
  docroot/modules/custom/uiowa_core/src/Commands/CpuTimeTrait.php
  docroot/modules/custom/uiowa_core/src/Entity/Page.php
  docroot/modules/custom/uiowa_core/src/EntityItemProcessorBase.php
  docroot/modules/custom/uiowa_core/src/EntityProcessorBase.php
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/modules/custom/uiowa_facilities/src/BizHubApiClient.php
  docroot/modules/custom/uiowa_facilities/src/BizHubApiClientInterface.php
  docroot/modules/custom/uiowa_facilities/src/BuildUiApiClient.php
  docroot/modules/custom/uiowa_facilities/src/BuildUiApiClientInterface.php
  docroot/modules/custom/uiowa_facilities/src/FacilitiesAPI.php
  docroot/modules/custom/uiowa_facilities/uiowa_facilities.services.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/BuildingsProcessor.php
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/Commands/FacilitiesCoreCommands.php
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/ProjectsProcessor.php
  docroot/sites/its.uiowa.edu/modules/its_core/src/Commands/ITSCoreCommands.php
Labels: dependencies, needs scheduled deployment

#7544 Sprint 207 Facilities work
  config/sites/facilities.uiowa.edu/field.field.node.alert.field_alert_traffic_control_plan.yml
  config/sites/facilities.uiowa.edu/views.view.projects.yml
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
Labels: facilities.uiowa.edu

#7554 [Brand P2LB] Permissions cleanup
  config/sites/brand.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/brand.uiowa.edu/config_split.patch.user.role.webmaster.yml
Labels: Just do it

#7570 Facilities Building Coordinators API hotfix
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/BuildingsProcessor.php
Labels: bug

#7564 [Aggregator] Decode raw html in title
  docroot/modules/custom/uiowa_aggregator/uiowa_aggregator.module
Labels: bug

#7616 [Commencement] Updated and exported permissions for venues
  config/sites/commencement.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/commencement.uiowa.edu/config_split.patch.user.role.publisher.yml
  config/sites/commencement.uiowa.edu/config_split.patch.user.role.viewer.yml
  config/sites/commencement.uiowa.edu/config_split.patch.user.role.webmaster.yml
Labels: commencement.uiowa.edu

#7619 Brand - fix service being called for this email
  docroot/sites/brand.uiowa.edu/modules/brand_core/brand_core.module
Labels: bug

#7629 Classrooms - loop properly over all bundles
  docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/src/RoomItemProcessor.php
Labels: bug
