Repository uiowa/uiowa, pull requests merged in 2024-08, with the labels that each got.

#7956 [Bug] Fix for mobile menu and banners
  docroot/themes/custom/uids_base/uids_base.libraries.yml
Labels: bug

#7961 [Registrar] Removed full calendar libraries no longer used
  docroot/sites/registrar.uiowa.edu/modules/registrar_core/registrar_core.libraries.yml
Labels: bug

#7925 [Bug] Blockquote
  config/default/layout_builder_styles.style.quote_left.yml
  docroot/modules/custom/sitenow_p2lb/sitenow_p2lb.module
  docroot/themes/custom/uids_base/package.json
  docroot/themes/custom/uids_base/scss/components/blockquote.scss
  docroot/themes/custom/uids_base/scss/layout-builder.scss
  docroot/themes/custom/uids_base/scss/sitenow_wysiwyg.scss
  docroot/themes/custom/uids_base/templates/block/block--inline-block--uiowa-quote.html.twig
  yarn.lock
Labels: bug, uids_base, uids

#7989 Update GPA Calculator module
  composer.lock
Labels: dependencies

#7995 Parallel deployment updates processing
  blt/src/Blt/Plugin/Commands/ReplaceCommands.php
Labels: automation

#8008 [Registrar] Adding missing :focus for calendar month checkbox
  docroot/sites/registrar.uiowa.edu/modules/registrar_core/css/academic_calendar.css
  docroot/sites/registrar.uiowa.edu/modules/registrar_core/src/Plugin/Block/AcademicCalendarBlock.php
Labels: Just do it
