Repository uiowa/uiowa, pull requests merged in 2024-02, with the labels that each got.

#7330 Fixed use strict in lazy load.
  docroot/themes/custom/uids_base/assets/js/lazy_load_animation.js
Labels: bug, Just do it

#7366 Fix for buildings import
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/src/BuildingItemProcessor.php
Labels: bug

#7389 Add warning to media delete with usage
  config/default/entity_usage.settings.yml
  docroot/profiles/custom/sitenow/sitenow.profile
Labels: gone rogue

#7396 Ctools 4
  composer.json
  composer.lock
  config/default/views.view.article_list_block.yml
  config/default/views.view.articles_author.yml
  config/default/views.view.people_list_block.yml
  config/features/event/views.view.events.yml
  config/features/event/views.view.events_list_block.yml
  config/features/sitenow_alerts/views.view.alerts_list_block.yml
  config/sites/admissions.uiowa.edu/views.view.community_colleges.yml
  config/sites/admissions.uiowa.edu/views.view.majors.yml
  config/sites/admissions.uiowa.edu/views.view.student_card.yml
  config/sites/classrooms.uiowa.edu/views.view.room_list.yml
  config/sites/facilities.uiowa.edu/views.view.artwork.yml
  config/sites/facilities.uiowa.edu/views.view.building_list.yml
  config/sites/facilities.uiowa.edu/views.view.named_building_list.yml
  config/sites/facilities.uiowa.edu/views.view.projects.yml
  config/sites/iisc.uiowa.edu/config_split.patch.core.entity_form_display.node.article.minimal.yml
  config/sites/iisc.uiowa.edu/views.view.article_related_content.yml
  config/sites/iisc.uiowa.edu/views.view.iisc_partners.yml
  config/sites/iisc.uiowa.edu/views.view.iisc_projects.yml
  config/sites/its.uiowa.edu/views.view.alerts_list_block.yml
  config/sites/its.uiowa.edu/views.view.services.yml
  config/sites/uipress.uiowa.edu/views.view.author_of.yml
  config/sites/uipress.uiowa.edu/views.view.homepage_books.yml
  docroot/modules/custom/layout_builder_custom/src/Plugin/Display/ListBlock.php
Labels: dependencies
