Repository uiowa/uiowa, pull requests merged in 2025-01, with the labels that each got.

#8389 Sprint 244 Requests
  blt/manifest.yml
  docroot/sites/cuwip.physics.uiowa.edu/blt.yml
  docroot/sites/cuwip.physics.uiowa.edu/default.local.drush.yml
  docroot/sites/cuwip.physics.uiowa.edu/default.settings.php
  docroot/sites/cuwip.physics.uiowa.edu/settings.php
  docroot/sites/cuwip.physics.uiowa.edu/settings/default.includes.settings.php
  docroot/sites/cuwip.physics.uiowa.edu/settings/default.local.settings.php
  docroot/sites/sites.php
  drush/sites/physicscuwip.site.yml
Labels: deprovision

#8398 Card Block - separate card switch with a break to avoid issues
  docroot/modules/custom/layout_builder_custom/layout_builder_custom.module
Labels: bug, gone rogue

#8426 Hawk Alert - remove param it is now returning a 400 bad request
  docroot/modules/custom/uiowa_alerts/es6/alerts.es6
Labels: bug

#8416 [Bug] Search toggle fix for off-brand sites
  docroot/themes/custom/uids_base/scss/components/logo.scss
  docroot/themes/custom/uids_base/scss/components/search-toggle.scss
Labels: bug

#8446 [Bug Hotfix] Image block caption bug fix
  docroot/themes/custom/uids_base/scss/components/image.scss
  docroot/themes/custom/uids_base/scss/media/media--type-image.scss
Labels: bug

#8443 [Bug Hotfix] Fix for chrome and edge modal
  docroot/themes/custom/uids_base/scss/admin.scss
Labels: bug

#8427 [Bug] Added fix for education field line breaks
  docroot/themes/custom/uids_base/scss/content/person.scss
Labels: bug

#8449 Grad - Scholar updates
  config/sites/grad.uiowa.edu/pathauto.pattern.scholars.yml
  config/sites/grad.uiowa.edu/views.view.srop_scholars.yml
  docroot/modules/custom/grad_custom/grad_custom.module
Labels: grad

#8458 Temporarily ignore release
  composer.json
Labels: dependencies, hotfix
