Repository uiowa/uiowa, pull requests merged in 2025-03, with the labels that each got.

#8559 New Relic - remove. didn't seem to work
  docroot/sites/settings/global.settings.php
Labels: gone rogue

#8607 Updated to Drupal 10.3.14.
  composer.lock
Labels: dependencies

#8622 [Mobile menu] Fixed aggregation issue where mobile menu is not collapsing
  docroot/themes/custom/uids_base/uids_base.libraries.yml
Labels: bug
