Repository uiowa/uiowa, pull requests merged in 2025-07, with the labels that each got.

#8978 Grad Neuroscience - re-export after recreating all affected filters across view displays
  config/sites/neuroscience.grad.uiowa.edu/views.view.person_custom.yml
Labels: bug

#8991 Update logic for site config in UMD command
  blt/src/Blt/Plugin/Commands/MultisiteCommands.php
Labels: bug, automation, gone rogue

#8997 [Hotfix] Added fixes for broken views
  config/sites/admissions.uiowa.edu/views.view.counselors.yml
  config/sites/amcs.uiowa.edu/views.view.custom_people.yml
  config/sites/pharmacy.uiowa.edu/views.view.palliative_grad.yml
  config/sites/uipress.uiowa.edu/views.view.author_page.yml
Labels: bug

#8996 Bus predictions style changes.
  docroot/modules/custom/sitenow_signage/js/bus_arrivals.js
  docroot/modules/custom/sitenow_signage/sass/signage.scss
  docroot/modules/custom/sitenow_signage/sitenow_signage.module
  docroot/themes/custom/uids_base/package.json
  yarn.lock
Labels: Just do it

#9057 [Bug] Added fix for card centered icons
  docroot/themes/custom/uids_base/scss/components/card.scss
Labels: bug
