Repository uiowa/uiowa, pull requests merged in 2025-09, with the labels that each got.

#9134 Add conditional on page_bottom wrapper in html template
  docroot/themes/custom/uids_base/templates/layout/html.html.twig
Labels: bug, gone rogue

#9149 Aggregator/RSS Feed Block - Register cache tags for proper invalidation
  docroot/modules/custom/uiowa_aggregator/uiowa_aggregator.module
Labels: bug, gone rogue

#9180 Update footer policy link to new location
  docroot/themes/custom/uids_base/templates/uids/footer--socket-menu.twig
Labels: Just do it

#9202 [Bug] Fix for horizontal menu bug when it contains unpublished items
  docroot/themes/custom/uids_base/templates/navigation/menu.html.twig
Labels: bug

#9195 [Bug] Fix for empty ul rendering for superfish
  docroot/themes/custom/uids_base/templates/layout/header.html.twig
  docroot/themes/custom/uids_base/templates/navigation/superfish.html.twig
  docroot/themes/custom/uids_base/uids_base.theme
Labels: bug
