Repository uiowa/uiowa, pull requests merged in 2025-04, with the labels that each got.

#8646 Maintenance mode - ignore changes to the message
  config/default/config_ignore.settings.yml
Labels: bug, gone rogue

#8653 update honeypot settings and update module as instructed
  composer.json
  composer.lock
  config/default/honeypot.settings.yml
Labels: database update

#8658 [Bug] Added patch for toolbar menu so that Viewer can logout
  composer.json
  composer.lock
  patches/core-3310075.patch
Labels: bug

#8657 Configuration schema fixes
  composer.json
  composer.lock
  docroot/modules/custom/layout_builder_custom/config/schema/layout_builder_custom.schema.yml
  docroot/profiles/custom/sitenow/sitenow.install
Labels: database update, config update

#8661 [Bug] Fix webform data export
  composer.json
  composer.lock
Labels: gone rogue

#8664 Adjust caching method on footer login link
  docroot/modules/custom/uiowa_core/uiowa_core.module
Labels: bug, gone rogue

#8675 Coding standards - Empty PHP statement detected: superfluous semicolon.
  docroot/modules/custom/layout_builder_custom/src/Plugin/diff/Field/LayoutSectionFieldBuilder.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/process/ExtractSummary.php
  docroot/modules/custom/sitenow_migrate/src/Plugin/migrate/process/MapTaxonomy.php
  docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/Achievement.php
  docroot/sites/now.uiowa.edu/modules/now_migrate/src/Plugin/migrate/source/NewsFeature.php
Labels: gone rogue

#8677 Security/Travis fixes
  .travis.yml
  composer.lock
Labels: database update

#8698 Fix undefined child_heading_size
  docroot/modules/custom/layout_builder_custom/src/Plugin/Field/FieldWidget/UiowaHeadlineWidget.php
Labels: bug, gone rogue
