Repository uiowa/uiowa, pull requests merged in 2025-06, with the labels that each got.

#8833 Signage - Move slides to sign
  config/default/config_split.config_split.signage.yml
  config/features/signage/block_content.type.slideshow.yml
  config/features/signage/core.entity_form_display.block_content.slideshow.default.yml
  config/features/signage/core.entity_form_display.node.sign.default.yml
  config/features/signage/core.entity_form_display.node.sign.minimal.yml
  config/features/signage/core.entity_form_display.node.slide.minimal.yml
  config/features/signage/core.entity_view_display.block_content.slideshow.default.yml
  config/features/signage/core.entity_view_display.node.sign.default.yml
  config/features/signage/core.entity_view_display.node.sign.teaser.yml
  config/features/signage/field.field.node.sign.field_sign_slides.yml
  config/features/signage/field.field.node.sign.layout_builder__layout.yml
  config/features/signage/field.storage.node.field_sign_slides.yml
  config/features/signage/user.role.sign_manager.yml
  docroot/modules/custom/sitenow_signage/sass/signage.scss
  docroot/modules/custom/sitenow_signage/sitenow_signage.module
  docroot/modules/custom/sitenow_signage/templates/field--node--field-sign-slides--sign--default.html.twig
Labels: signage.uiowa.edu

#8825 Logrotate revisited
  blt/src/Blt/Plugin/Commands/ReplaceCommands.php
  logrotate.conf
Labels: gone rogue

#8864 Updated crop and focal_point modules
  composer.json
  composer.lock
Labels: dependencies

#8862 [bef] Removed jquery_ui modules and bef from splits
  composer.json
  composer.lock
  config/sites/admissions.uiowa.edu/config_split.config_split.site.yml
  config/sites/classrooms.uiowa.edu/config_split.config_split.site.yml
  config/sites/housing.uiowa.edu/config_split.config_split.site.yml
  config/sites/iisc.uiowa.edu/config_split.config_split.site.yml
Labels: Just do it

#8902 Classrooms building filter fixes
  config/sites/classrooms.uiowa.edu/views.view.room_list.yml
  docroot/modules/custom/uiowa_core/uiowa_core.module
  docroot/sites/classrooms.uiowa.edu/modules/classrooms_core/classrooms_core.module
Labels: bug

#8947 Hotfix - add schema alter info for custom fields on basic site settings form
  docroot/modules/custom/uiowa_core/uiowa_core.module
Labels: bug

#8948 Facilities - fix view config and sort artists by label
  config/sites/facilities.uiowa.edu/views.view.artwork.yml
  docroot/modules/custom/uiowa_core/src/Plugin/views/filter/EntityReferenceOverride.php
  docroot/sites/facilities.uiowa.edu/modules/facilities_core/facilities_core.module
Labels: bug, facilities.uiowa.edu
