Repository uiowa/uiowa, pull requests merged in 2025-05, with the labels that each got.

#8714 hotfix - resave default content after issues with new site installs
  composer.json
  composer.lock
  docroot/profiles/custom/sitenow/content/block_content/30a2799f-c1bf-4ce5-a8f3-0bd71141a580.yml
  docroot/profiles/custom/sitenow/content/block_content/3e775397-cb1e-40de-9c53-f00e328edc2d.yml
  docroot/profiles/custom/sitenow/content/block_content/41c43a1b-0473-45b1-b799-2b235c3904fb.yml
  docroot/profiles/custom/sitenow/content/block_content/4b3a0581-6c84-4417-b6ea-3eb5e9bd9d50.yml
  docroot/profiles/custom/sitenow/content/block_content/5fd3432c-7324-4dc5-bfa1-54d07b43da77.yml
  docroot/profiles/custom/sitenow/content/block_content/631979b9-cf39-46d2-a357-e8857487fccd.yml
  docroot/profiles/custom/sitenow/content/block_content/8a740559-85c3-45d3-beb4-776806a82a79.yml
  docroot/profiles/custom/sitenow/content/block_content/ab5ad35a-4275-492b-aa5a-3c6a5f94ae9b.yml
  docroot/profiles/custom/sitenow/content/block_content/b8aba3a5-10de-42ad-8cb1-dee195b4d540.yml
  docroot/profiles/custom/sitenow/content/block_content/c45277c6-60d5-44fb-9d00-689687a550ec.yml
  docroot/profiles/custom/sitenow/content/block_content/e8a1a5d7-a7c6-4b59-a13d-ee498ec7232c.yml
  docroot/profiles/custom/sitenow/content/block_content/e92499d4-4692-4937-882f-4abb975e6e85.yml
  docroot/profiles/custom/sitenow/content/block_content/e9b591a5-24cf-45a7-aeba-334f82fd6549.yml
  docroot/profiles/custom/sitenow/content/media/0005b838-46f9-4c0f-a669-be81fa5bd03a.yml
  docroot/profiles/custom/sitenow/content/media/3d1939ab-0a2b-41da-910e-252aee65523a.yml
  docroot/profiles/custom/sitenow/content/media/65f9eae1-f80b-4b14-b495-ff3bd2551762.yml
  docroot/profiles/custom/sitenow/content/media/67599837-9a35-4165-b0a6-2b5b0a87a61e.yml
  docroot/profiles/custom/sitenow/content/media/99436d77-db6b-43b8-8e04-ea2f0e62b590.yml
  docroot/profiles/custom/sitenow/content/media/be324113-25ee-43e3-b6f2-26ce619ce852.yml
  docroot/profiles/custom/sitenow/content/media/c064e28e-aae9-42f5-bb15-f40fa1d8a3d7.yml
  docroot/profiles/custom/sitenow/content/media/c7ad7c5d-0097-43b9-bc22-b479b5d30ac1.yml
  docroot/profiles/custom/sitenow/content/media/d872b41f-45af-4c94-9054-56d249130203.yml
  docroot/profiles/custom/sitenow/content/media/e40c44de-579d-4b50-9e5e-5b0c304564ff.yml
  docroot/profiles/custom/sitenow/content/media/fc23ffc0-95e1-45ff-ab07-b92464068d66.yml
  docroot/profiles/custom/sitenow/content/node/922b3b26-306a-457c-ba18-2c00966f81cf.yml
  docroot/profiles/custom/sitenow/content/node/f44a17cb-a187-4286-ad9f-aae44a8e9f85.yml
Labels: bug

#8719 [Brand] Added bug fix for lockup arrows
  config/sites/brand.uiowa.edu/views.view.lockups.yml
Labels: bug

#8720 [Photoswipe] Added fix for image gallery stretching.
  docroot/themes/custom/uids_base/scss/components/image-gallery-block.scss
Labels: bug

#8733 Add HSTS header to .htaccess
  docroot/.htaccess
  patches/core_htaccess.patch
Labels: donotmerge

#8752 Remove "Add Views EntityReference filter to be available for all entity reference fields" patch
  composer.json
  composer.lock
Labels: gone rogue, DX

#8744 [Bug] Adjusted how banner is attached to slider component.
  docroot/themes/custom/uids_base/uids_base.libraries.yml
Labels: bug

#8695 [HR] Site split cleanup
  config/sites/hr.uiowa.edu/config_split.config_split.site.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_form_display.node.article.default.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_form_display.node.article.minimal.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_form_display.node.page.default.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_view_display.node.article.default.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_view_display.node.article.teaser.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_view_display.node.article.token.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_view_display.node.page.banner.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_view_display.node.page.teaser.yml
  config/sites/hr.uiowa.edu/config_split.patch.core.entity_view_display.node.page.token.yml
  config/sites/hr.uiowa.edu/config_split.patch.user.role.editor.yml
  config/sites/hr.uiowa.edu/config_split.patch.user.role.webmaster.yml
  config/sites/hr.uiowa.edu/config_split.patch.workflows.workflow.editorial.yml
  config/sites/hr.uiowa.edu/core.entity_view_display.node.page.default.yml
  config/sites/hr.uiowa.edu/field.field.node.article.field_reference.yml
  config/sites/hr.uiowa.edu/field.field.node.page.field_reference.yml
  config/sites/hr.uiowa.edu/field.storage.node.field_reference.yml
  docroot/sites/hr.uiowa.edu/modules/hr_core/hr_core.install
Labels: donotmerge

#8745 Layout clean up
  docroot/modules/custom/uiowa_core/src/Plugin/Layout/MultiWidthLayoutBase.php
  docroot/modules/custom/uiowa_core/src/Plugin/Layout/TwoColumnLayout.php
  docroot/profiles/custom/sitenow/sitenow.install
  docroot/themes/custom/uids_base/uids_base.layouts.yml
Labels: gone rogue, DX, needs scheduled deployment

#8761 [Hotfix] Commencement
  composer.json
  composer.lock
Labels: bug

#8759 [a11y] Accordion lists
  docroot/themes/custom/uids_base/package.json
  yarn.lock
Labels: a11y

#8769 Updated to pwiki_pro 1.3.2
  composer.json
  composer.lock
Labels: dependencies

#8762 [better_exposed_filters] ^7.0
  composer.json
  composer.lock
  config/features/event/views.view.events.yml
  config/sites/admissions.uiowa.edu/views.view.areas_of_study.yml
  config/sites/admissions.uiowa.edu/views.view.areas_of_study_kiosk.yml
  config/sites/classrooms.uiowa.edu/views.view.room_list.yml
  config/sites/commencement.uiowa.edu/views.view.ceremonies.yml
  config/sites/facilities.uiowa.edu/views.view.building_list.yml
  config/sites/housing.uiowa.edu/views.view.residence_halls.yml
  config/sites/iisc.uiowa.edu/views.view.iisc_projects.yml
  config/sites/inrc.law.uiowa.edu/views.view.grants.yml
  config/sites/inrc.law.uiowa.edu/views.view.nonprofit_organization.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.views.view.events.yml
  config/sites/its.uiowa.edu/views.view.alerts_list_block.yml
  config/sites/iwp.uiowa.edu/views.view.resources.yml
  config/sites/wellbeing.uiowa.edu/config_split.patch.views.view.page_list_block.yml
  docroot/themes/custom/uids_base/scss/views/bef/view-bef.scss
Labels: dependencies

#8778 dependabot.yml update
  .github/dependabot.yml
Labels: dependencies

#8777 Updated address module to 2.0.4
  composer.json
  composer.lock
  config/default/core.entity_form_display.paragraph.uiowa_contact.default.yml
  config/features/contact/core.entity_form_display.node.contact.default.yml
  config/features/event/core.entity_form_display.node.event.default.yml
  config/sites/commencement.uiowa.edu/core.entity_form_display.node.venue.default.yml
  config/sites/inrc.law.uiowa.edu/core.entity_form_display.node.grant.default.yml
  config/sites/inrc.law.uiowa.edu/core.entity_form_display.node.nonprofit_org.default.yml
  config/sites/iowasummerwritingfestival.uiowa.edu/config_split.patch.core.entity_form_display.node.event.default.yml
Labels: dependencies, database update, config update

#8788 Updated simple sitemap to 4.2.2
  composer.json
  composer.lock
  config/default/simple_sitemap.sitemap.default.yml
  config/default/simple_sitemap.type.default_hreflang.yml
  config/default/simple_sitemap.type.index.yml
Labels: database update
