Repository uiowa/uiowa, pull requests merged in 2025-02, with the labels that each got.

#8468 [Featured content] Background colors
  config/default/layout_builder_styles.style.block_background_style_black.yml
  config/default/layout_builder_styles.style.block_background_style_gold.yml
  config/default/layout_builder_styles.style.block_background_style_gray.yml
  config/default/layout_builder_styles.style.block_background_style_light.yml
Labels: stories.uiowa.edu, Just do it

#8493 New Relic - Reduce error noise
  docroot/sites/settings/global.settings.php
Labels: gone rogue

#8496 [a11y] Academic dates card field fix
  docroot/modules/custom/uiowa_maui/css/session-dates.css
  docroot/modules/custom/uiowa_maui/src/Form/AcademicDatesForm.php
  docroot/modules/custom/uiowa_maui/uiowa_maui.module
Labels: a11y

#8502 [Registrar] file archive bug
  config/sites/registrar.uiowa.edu/views.view.file_archive.yml
Labels: bug

#8472 [Bug] Headline class namespace collision with profiles directory
  docroot/themes/custom/uids_base/templates/uids/headline.html.twig
Labels: bug

#8536 [Bug] Added workaround leaflet init library to pharmacy and admissions maps
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/js/counselors-map.js
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/sass/counselors-map.scss
  docroot/sites/admissions.uiowa.edu/modules/admissions_core/src/Plugin/Block/AdmissionsCounselorsMapBlock.php
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/js/palliative-grad-map.js
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/pharmacy_core.module
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/sass/palliative-grad-map.scss
  docroot/sites/pharmacy.uiowa.edu/modules/pharmacy_core/src/Plugin/Block/PalliativeGradMapBlock.php
Labels: bug
